// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class acactivo_kit
    {
        public int? codactivo { get; set; }
        public int? codactivo_parte { get; set; }
        public DateTime? fechareg { get; set; }
        public string usuarioreg { get; set; }
        public string horareg { get; set; }
    }
}