// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class acdepreciacion1
    {
        public int codplanilla { get; set; }
        public int codactivo { get; set; }
        public decimal? tdcactual { get; set; }
        public decimal? tdcnuevo { get; set; }
        public decimal ValActual { get; set; }
        public decimal IncActualizacion1 { get; set; }
        public decimal ValActualizado { get; set; }
        public decimal DepreActual { get; set; }
        public decimal IncActualizacion2 { get; set; }
        public decimal DepreActualizada { get; set; }
        public decimal DeprePeriodo { get; set; }
        public decimal DepreAcumulada { get; set; }
        public decimal ValResidual { get; set; }
        public decimal RestoVidaUtil { get; set; }
    }
}