// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class acmantenimiento1
    {
        public int codmantenimiento { get; set; }
        public string descripcion { get; set; }
        public decimal monto { get; set; }
    }
}