// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class acrevaluo
    {
        public int codigo { get; set; }
        public int codactivo { get; set; }
        public DateTime fechaant { get; set; }
        public decimal costoant { get; set; }
        public decimal tipocambioant { get; set; }
        public string monedaant { get; set; }
        public string obs { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
    }
}