// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class adacceso1
    {
        public int codigo { get; set; }
        public int codprog { get; set; }
        public byte orden { get; set; }
        public int dias { get; set; }
    }
}