// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class adarea
    {
        public int codigo { get; set; }
        public string descripcion { get; set; }
        public string empresa { get; set; }
        public string ciudad { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
    }
}