// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class adaudit_totventas
    {
        public int? anio { get; set; }
        public byte? mes { get; set; }
        public string por { get; set; }
        public string tipo { get; set; }
        public string codigo { get; set; }
        public decimal? tot { get; set; }
        public decimal? totpp { get; set; }
        public decimal? totp { get; set; }
        public decimal? totv { get; set; }
        public decimal? totsd { get; set; }
        public string codmoneda { get; set; }
    }
}