// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class adaudit_compraslinea_unir
    {
        public string codcliente { get; set; }
        public string codcliente2 { get; set; }
    }
}