// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class adaudit_visitas_ptoventa
    {
        public int? codptoventa { get; set; }
        public int? diasventa { get; set; }
        public int? diasvisita { get; set; }
    }
}