// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class adaudit_visitas
    {
        public int codigo { get; set; }
        public byte? tipo { get; set; }
        public int? codvendedor { get; set; }
        public string codcliente { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public DateTime? fecha { get; set; }
        public string motivo { get; set; }
        public decimal? monto { get; set; }
        public int? duracion { get; set; }
        public string resultado { get; set; }
        public DateTime? hora { get; set; }
        public DateTime? fechacon { get; set; }
        public DateTime? hasta { get; set; }
        public string contacto { get; set; }
    }
}