// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class adsiat_sucursal
    {
        public int codsucursal { get; set; }
        public int codalmacen { get; set; }
        public string direccion { get; set; }
        public bool? generar_masivo { get; set; }
        public DateTime fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
    }
}