// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class adsiat_cufd
    {
        public int codigo { get; set; }
        public string codsistema { get; set; }
        public int codalmacen { get; set; }
        public DateTime desde_fecha { get; set; }
        public string desdehr { get; set; }
        public DateTime hasta_fecha { get; set; }
        public string hastahr { get; set; }
        public string cufd { get; set; }
        public string codigo_control { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
    }
}