// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class adtablas_sia
    {
        public int codigo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public bool? imprimir { get; set; }
        public string modulo { get; set; }
        public decimal? nro_modulo { get; set; }
    }
}