// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class adversion_sia_conexion
    {
        public string agencia { get; set; }
        public int? codalmacen { get; set; }
        public string ip { get; set; }
        public string folder_versiones { get; set; }
        public string folder_version_actual { get; set; }
    }
}