// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class audit_descuentos_mensual
    {
        public int? codalmacen { get; set; }
        public int? mes { get; set; }
        public int? anio { get; set; }
        public string codcliente_main { get; set; }
        public string codcliente { get; set; }
        public string razonsocial { get; set; }
        public string clasificacion { get; set; }
        public int? codgrupo { get; set; }
        public string nivel { get; set; }
        public decimal? objetivo { get; set; }
        public decimal? promedio { get; set; }
        public decimal? porcentaje { get; set; }
        public string nuevo_nivel { get; set; }
        public int? cuantos_bajar { get; set; }
        public int? cambiar { get; set; }
        public decimal? objetivo_subir { get; set; }
        public string nivel_subir { get; set; }
    }
}