// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class borrar_1
    {
        public string coditem { get; set; }
        public string descripcion { get; set; }
        public string medida { get; set; }
        public decimal? ajuste2826 { get; set; }
        public decimal? ajuste2827 { get; set; }
        public decimal? anuladas_1 { get; set; }
        public decimal? anuladas_2 { get; set; }
    }
}