// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class cc_3447153
    {
        public string codcuenta { get; set; }
        public string nombrecuenta { get; set; }
        public string auxiliar { get; set; }
        public bool? imputable { get; set; }
        public int? tipo { get; set; }
        public decimal? cc_100 { get; set; }
        public decimal? cc_108 { get; set; }
        public decimal? cc_310 { get; set; }
        public decimal? cc_311 { get; set; }
        public decimal? cc_312 { get; set; }
        public decimal? cc_313 { get; set; }
        public decimal? cc_314 { get; set; }
    }
}