// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class cmconcepto_tiendas
    {
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public decimal? porcen_ice { get; set; }
        public decimal? porcen_retencion { get; set; }
        public string horareg { get; set; }
        public DateTime? fechareg { get; set; }
        public string usuarioreg { get; set; }
        public decimal? porcen_it { get; set; }
        public decimal? porcen_iva { get; set; }
        public decimal? balance { get; set; }
        public DateTime? fecha { get; set; }
        public string codmoneda { get; set; }
        public bool? usarconfactura { get; set; }
        public bool? usarsinfactura { get; set; }
        public bool? servicio { get; set; }
    }
}