// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class cmprovision_cc
    {
        public int? codcentrocosto { get; set; }
        public decimal? monto { get; set; }
        public int? codprovision_concepto { get; set; }
    }
}