// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class cn_revision
    {
        public string id { get; set; }
        public int? numeroid { get; set; }
    }
}