// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class cnajustesme
    {
        public string codempresa { get; set; }
        public int codcentrocosto { get; set; }
        public byte mes { get; set; }
        public int anio { get; set; }
    }
}