// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class cncomprobante1_backup
    {
        public int codcomprobante { get; set; }
        public string cuenta { get; set; }
        public int? centrocosto { get; set; }
        public string detalle { get; set; }
        public decimal factor { get; set; }
        public decimal debe { get; set; }
        public decimal haber { get; set; }
        public string monedacta { get; set; }
        public short? nro { get; set; }
        public bool? ajuste { get; set; }
    }
}