// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class cnlibromayor
    {
        public int codigo { get; set; }
        public int codalmacen { get; set; }
        public int? centrocosto { get; set; }
        public string codcuenta { get; set; }
        public string auxiliar { get; set; }
        public DateTime fecha { get; set; }
        public string detalle { get; set; }
        public int codcomprobante { get; set; }
        public decimal debe { get; set; }
        public decimal haber { get; set; }
        public byte tipo { get; set; }
        public decimal? tdc { get; set; }
        public string monedacta { get; set; }
        public bool ajuste { get; set; }
        public decimal debee { get; set; }
        public decimal habere { get; set; }
        public int? nro { get; set; }
        public string tipo_gasto { get; set; }
    }
}