// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class cnmixto
    {
        public int? codalmacen { get; set; }
        public int? codvendedor { get; set; }
        public string auxiliar { get; set; }
    }
}