// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class cnmoldebg2
    {
        public string codmoldebg { get; set; }
        public int? nro { get; set; }
        public string codcuenta { get; set; }
    }
}