// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class cnresumenie_23
    {
        public string codcuenta { get; set; }
        public string nombrecuenta { get; set; }
        public string auxiliar { get; set; }
        public bool? imputable { get; set; }
        public int? tipo { get; set; }
        public decimal? ENERO_2015 { get; set; }
        public decimal? FEBRERO_2015 { get; set; }
        public decimal? MARZO_2015 { get; set; }
        public decimal? ABRIL_2015 { get; set; }
        public decimal? MAYO_2015 { get; set; }
        public decimal? JUNIO_2015 { get; set; }
        public decimal? JULIO_2015 { get; set; }
        public decimal? AGOSTO_2015 { get; set; }
        public decimal? SEPTIEMBRE_2015 { get; set; }
        public decimal? OCTUBRE_2015 { get; set; }
        public decimal? NOVIEMBRE_2015 { get; set; }
        public decimal? DICIEMBRE_2015 { get; set; }
    }
}