// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class cnresumenap_aux
    {
        public string codcuenta { get; set; }
        public string nombrecuenta { get; set; }
        public string auxiliar { get; set; }
        public bool? imputable { get; set; }
        public int? tipo { get; set; }
        public decimal? ENERO_2011 { get; set; }
        public decimal? FEB_2011 { get; set; }
        public decimal? MAR_2011 { get; set; }
        public decimal? ABR_2011 { get; set; }
        public decimal? MAYO_2011 { get; set; }
        public decimal? JUNIO_2011 { get; set; }
        public decimal? JULIO_2011 { get; set; }
        public decimal? AGOSTO_2011 { get; set; }
        public decimal? SEP_2011 { get; set; }
        public decimal? OCT_2011 { get; set; }
        public decimal? NOV_2011 { get; set; }
        public decimal? DIC_2011 { get; set; }
        public decimal? ENERO_2012 { get; set; }
        public decimal? FEBR_2012 { get; set; }
        public decimal? MAR_2012 { get; set; }
        public decimal? ABR_2012 { get; set; }
        public decimal? MAY_2012 { get; set; }
        public decimal? JUN_2012 { get; set; }
        public decimal? JUL_2012 { get; set; }
        public decimal? AGO_2012 { get; set; }
        public decimal? SEPT_2012 { get; set; }
        public decimal? OCT_2012 { get; set; }
        public decimal? NOV_2012 { get; set; }
        public decimal? DIC_2012 { get; set; }
        public decimal? ENE_2013 { get; set; }
        public decimal? FEB_2013 { get; set; }
        public decimal? MAR_2013 { get; set; }
        public decimal? ABR_2013 { get; set; }
        public decimal? MAY_2013 { get; set; }
        public decimal? JUN_2013 { get; set; }
        public decimal? JUL_2013 { get; set; }
        public decimal? JULIO_2013 { get; set; }
        public decimal? AGOSTO_13 { get; set; }
        public decimal? SEP_2013 { get; set; }
        public decimal? OCT_2013 { get; set; }
        public decimal? OCTUBRE_2013 { get; set; }
        public decimal? NOV_2013 { get; set; }
        public decimal? ENE_2012 { get; set; }
        public decimal? FEBRERO_2 { get; set; }
        public decimal? MARZO_2012 { get; set; }
        public decimal? ABRIL_2012 { get; set; }
        public decimal? MAYO_2012 { get; set; }
        public decimal? JUNIO_2012 { get; set; }
        public decimal? JULIO_2012 { get; set; }
        public decimal? AGOSTO_2012 { get; set; }
        public decimal? SEPTIEMBRE_2012 { get; set; }
        public decimal? OCTUBRE_2012 { get; set; }
        public decimal? NOVIEMBRE_2012 { get; set; }
        public decimal? DICIEMBRE_2012 { get; set; }
    }
}