// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class cnsumasysaldos1
    {
        public int codsumasysaldos { get; set; }
        public string codcuenta { get; set; }
        public decimal debe { get; set; }
        public decimal haber { get; set; }
        public decimal deudor { get; set; }
        public decimal acreedor { get; set; }
    }
}