// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class codescuento_mora
    {
        public int codigo { get; set; }
        public int? codpersona { get; set; }
        public decimal? total { get; set; }
        public string codmoneda { get; set; }
        public DateTime? fecha { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
        public bool? aplicado { get; set; }
        public bool? anulado { get; set; }
        public string id { get; set; }
        public int? numeroid { get; set; }
        public int? codalmacen { get; set; }
        public string id_remision { get; set; }
        public int? numeroid_remision { get; set; }
        public int? nrocuota { get; set; }
        public int? codvendedor { get; set; }
        public int? codcargo { get; set; }
        public int? dias_mora { get; set; }
        public decimal? saldo_en_mora { get; set; }
        public string codmoneda_saldo_en_mora { get; set; }
        public decimal? porcentaje { get; set; }
        public bool? main { get; set; }
        public bool? autorizado { get; set; }
    }
}