// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class codevolucion_mora
    {
        public int codigo { get; set; }
        public int? anio { get; set; }
        public int? mes { get; set; }
        public int? codpersona { get; set; }
        public decimal? monto { get; set; }
        public string codmoneda { get; set; }
        public int? codcargo { get; set; }
        public string obs { get; set; }
        public string id_nr { get; set; }
        public int? nroid_nr { get; set; }
        public int? nrocuota { get; set; }
        public string id { get; set; }
        public int? numeroid { get; set; }
        public DateTime? fecha { get; set; }
        public string id_desctomora { get; set; }
        public int? numeroid_desctomora { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
    }
}