// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class codigo
    {
        public int codigo1 { get; set; }
        public DateTime? desde { get; set; }
        public DateTime? hasta { get; set; }
        public int? codarea { get; set; }
        public string obs { get; set; }
        public DateTime? fechareg { get; set; }
        public string usuarioreg { get; set; }
        public string horareg { get; set; }
    }
}