// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class comdpto_1110
    {
        public int? ano { get; set; }
        public int? mes { get; set; }
        public int? codvendedor { get; set; }
        public string dpto { get; set; }
        public int? g { get; set; }
        public string nd { get; set; }
        public decimal? comision { get; set; }
    }
}