// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class copagomora
    {
        public int codigo { get; set; }
        public string id { get; set; }
        public int numeroid { get; set; }
        public string descripcion { get; set; }
        public DateTime fecha { get; set; }
        public int vendedor { get; set; }
        public string cliente { get; set; }
        public decimal? monto { get; set; }
        public string moneda { get; set; }
        public int? tipopago { get; set; }
        public string codcuentab { get; set; }
        public string codbanco { get; set; }
        public string nrocheque { get; set; }
        public string codtalonario { get; set; }
        public int nrorecibo { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
        public int? codalmacen { get; set; }
        public bool? anulado { get; set; }
        public string idcuenta { get; set; }
        public string iddeudor_compuesto { get; set; }
        public decimal? monto_me { get; set; }
        public decimal? monto_cambio { get; set; }
        public bool? pordescuentopp { get; set; }
    }
}