// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class cpimportacionesporllegar
    {
        public string coditem { get; set; }
        public decimal cantidad { get; set; }
        public DateTime fecha { get; set; }
        public string importacion { get; set; }
    }
}