// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class cppreciocomp1
    {
        public int codpreciocomp { get; set; }
        public string coditem { get; set; }
        public decimal pu { get; set; }
        public string codmoneda { get; set; }
        public string codudm { get; set; }
        public bool f1 { get; set; }
        public decimal pfactor1 { get; set; }
        public bool f2 { get; set; }
        public decimal pfactor2 { get; set; }
        public bool f3 { get; set; }
        public decimal pfactor3 { get; set; }
    }
}