// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class cptransito
    {
        public int? codalmacen { get; set; }
        public int? anio { get; set; }
        public int? mes { get; set; }
        public string coditem { get; set; }
        public decimal? cantidad_kg { get; set; }
        public decimal? cantidad_ud { get; set; }
    }
}