// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class crconsolida_precios
    {
        public int? codtarifa { get; set; }
        public bool? consolida { get; set; }
    }
}