// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class crmcaso_detalle
    {
        public int codigo { get; set; }
        public string id { get; set; }
        public int? numeroid { get; set; }
        public int? tipo_reclamo { get; set; }
        public string reclamante { get; set; }
        public int? tel_cel { get; set; }
        public string correo { get; set; }
    }
}