// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class crmnota
    {
        public int codigo { get; set; }
        public string id { get; set; }
        public int? codcaso { get; set; }
        public string codcuenta { get; set; }
        public DateTime? fecha { get; set; }
        public string usuario { get; set; }
        public string asunto { get; set; }
        public string contenido { get; set; }
        public string usuario_d { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
        public bool? redireccionar_usr { get; set; }
        public string estado { get; set; }
        public string resultado { get; set; }
        public int? codasunto { get; set; }
    }
}