// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class crmodulo_excluido_vend
    {
        public string modulo { get; set; }
        public bool? excluir_importar { get; set; }
    }
}