// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class cscostoadicional
    {
        public int? mes { get; set; }
        public int? anio { get; set; }
        public decimal? porcen_costo { get; set; }
        public decimal? total_costo { get; set; }
        public decimal? porcen_retencion { get; set; }
        public decimal? total_retencion { get; set; }
        public int? codalmacen { get; set; }
        public decimal? total_venta { get; set; }
        public decimal? factor { get; set; }
        public decimal? costo_adicional { get; set; }
    }
}