// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class csgastoembarque_dist
    {
        public int codembarque { get; set; }
        public int codgasto { get; set; }
        public string coditem { get; set; }
        public decimal precio { get; set; }
        public bool? elegido { get; set; }
    }
}