// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class csiguales
    {
        public int codigo { get; set; }
        public string coditem_1 { get; set; }
        public string coditem_2 { get; set; }
        public string coditem_3 { get; set; }
        public string coditem_4 { get; set; }
        public string coditem_5 { get; set; }
        public string coditem_6 { get; set; }
        public string coditem_7 { get; set; }
        public string coditem_8 { get; set; }
        public string coditem_9 { get; set; }
        public string coditem_10 { get; set; }
    }
}