// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class es_ventas_cliente_linea1
    {
        public int? anio { get; set; }
        public int? mes { get; set; }
        public int? codalmacen { get; set; }
        public int? codvendedor { get; set; }
        public string codcliente { get; set; }
        public string razonsocial { get; set; }
        public string codgrupo_vta { get; set; }
        public string descgrupo { get; set; }
        public string codsubgrupo_vta { get; set; }
        public string descsubgrupo { get; set; }
        public string codlinea { get; set; }
        public string desclinea { get; set; }
        public string coditem { get; set; }
        public string descitem { get; set; }
        public string medida { get; set; }
        public decimal? ttl_kg { get; set; }
        public decimal? ttl_us { get; set; }
    }
}