// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class es_ventas_saldos
    {
        public int codigo { get; set; }
        public int? codalmacen { get; set; }
        public int? anio { get; set; }
        public int? mes { get; set; }
        public string tipo { get; set; }
        public string coditem_cjto { get; set; }
        public string coditem { get; set; }
        public decimal? ttl_kg { get; set; }
        public decimal? ttl_ud { get; set; }
        public decimal? ttl_me { get; set; }
        public decimal? ttl_mn { get; set; }
        public decimal? saldo_kg { get; set; }
        public decimal? saldo_ud { get; set; }
    }
}