// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class EstadoActual
    {
        public string cliente { get; set; }
        public int? codgrupo { get; set; }
        public string nivel { get; set; }
        public byte? estado { get; set; }
    }
}