// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class fdf
    {
        public int? codvendedor { get; set; }
        public string id { get; set; }
        public int? numeroid { get; set; }
        public string codcliente { get; set; }
        public decimal? pago { get; set; }
        public decimal? cobranza { get; set; }
        public DateTime? fecha { get; set; }
        public DateTime? vencimiento { get; set; }
        public int? dias { get; set; }
        public int? pp { get; set; }
        public int? dias_pp { get; set; }
        public int? ext { get; set; }
    }
}