// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class fncheque_cliente
    {
        public int codigo { get; set; }
        public string id { get; set; }
        public int? numeroid { get; set; }
        public int? codalmacen { get; set; }
        public string codcliente { get; set; }
        public string codmoneda { get; set; }
        public decimal? monto { get; set; }
        public decimal? montorest { get; set; }
        public DateTime? fecha { get; set; }
        public DateTime? fechapago { get; set; }
        public bool anulado { get; set; }
        public string codtalonario { get; set; }
        public int? nrorecibo { get; set; }
        public string codbanco { get; set; }
        public string nrocheque { get; set; }
        public string obs { get; set; }
        public string horareg { get; set; }
        public DateTime? fechareg { get; set; }
        public string usuarioreg { get; set; }
        public bool? rechazado { get; set; }
        public DateTime? fecha_rechazado { get; set; }
    }
}