// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class fndeposito
    {
        public int codigo { get; set; }
        public string id { get; set; }
        public int? numeroid { get; set; }
        public int? codalmacen { get; set; }
        public DateTime? fecha { get; set; }
        public string idcuenta { get; set; }
        public string codcuentab { get; set; }
        public decimal? monto { get; set; }
        public string codmoneda { get; set; }
        public decimal? factorme { get; set; }
        public string memo { get; set; }
        public bool anulada { get; set; }
        public bool contabilizada { get; set; }
        public int? comprobante { get; set; }
        public string horareg { get; set; }
        public DateTime? fechareg { get; set; }
        public string usuarioreg { get; set; }
        public decimal? itf { get; set; }
        public decimal? tdc { get; set; }
        public DateTime? fecha_conta { get; set; }
        public DateTime? fecha_anulacion { get; set; }
        public int? codvendedor { get; set; }
    }
}