// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class fnresumendiario_b
    {
        public int codigo { get; set; }
        public int? codalmacen { get; set; }
        public DateTime? fecha { get; set; }
        public decimal? tot_recuperaciones { get; set; }
        public decimal? tot_ingresos { get; set; }
        public decimal? saldo_anterior { get; set; }
        public decimal? tot_disponible { get; set; }
        public decimal? tot_egresos { get; set; }
        public decimal? saldo_mg { get; set; }
        public decimal? saldo_mc { get; set; }
        public decimal? saldo_ch { get; set; }
        public decimal? saldo_vl { get; set; }
        public decimal? dif_caja { get; set; }
        public decimal? saldo_caja { get; set; }
        public decimal? saldo_me { get; set; }
        public string responsable { get; set; }
        public string nroclientes { get; set; }
        public decimal? tot_ventas { get; set; }
        public decimal? saldome_mg { get; set; }
        public decimal? saldome_mc { get; set; }
        public decimal? saldome_ch { get; set; }
        public decimal? saldome_vl { get; set; }
        public decimal? difme_caja { get; set; }
        public decimal? dif_tdc { get; set; }
        public string obs { get; set; }
    }
}