// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class fnsaldo_librob
    {
        public string codcuentab { get; set; }
        public decimal? monto { get; set; }
        public string codmoneda { get; set; }
        public DateTime fecha { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
    }
}