// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class inalmacen_conta
    {
        public int? codalmacen { get; set; }
        public string codunidad { get; set; }
        public string cta { get; set; }
        public string cta_aux { get; set; }
        public int? cta_cc { get; set; }
        public string cta_costovta { get; set; }
        public string cta_costovta_aux { get; set; }
        public int? cta_costovta_cc { get; set; }
        public string cta_vendida { get; set; }
        public string cta_vendida_aux { get; set; }
        public int? cta_vendida_cc { get; set; }
    }
}