// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class incarga1
    {
        public int codcarga { get; set; }
        public decimal? cantbultos { get; set; }
        public string clase { get; set; }
        public string contenido { get; set; }
        public decimal? pesok { get; set; }
    }
}