// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class inetiquetas
    {
        public int codigo { get; set; }
        public string coditem { get; set; }
        public string linea1 { get; set; }
        public string linea2 { get; set; }
        public string linea3 { get; set; }
    }
}