// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class ingrupo_nivel
    {
        public int codigo { get; set; }
        public string descripcion { get; set; }
        public decimal NIVEL_E { get; set; }
        public decimal NIVEL_D { get; set; }
        public decimal NIVEL_C { get; set; }
        public decimal NIVEL_B { get; set; }
        public decimal NIVEL_A { get; set; }
    }
}