// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class initem_noreserva_saldo
    {
        public string coditem { get; set; }
        public string coditem1 { get; set; }
        public string coditem2 { get; set; }
    }
}