// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class inmaxmin
    {
        public int almacen { get; set; }
        public string item { get; set; }
        public int smax { get; set; }
        public int smin { get; set; }
        public int ptoped { get; set; }
        public string horareg { get; set; }
        public DateTime fecha { get; set; }
        public string Usuario { get; set; }
    }
}