// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class inpedido1
    {
        public int codpedido { get; set; }
        public string coditem { get; set; }
        public decimal cantidad { get; set; }
        public string udm { get; set; }
        public int? codproveedor { get; set; }
    }
}