// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class inplanudm1
    {
        public int codplanudm { get; set; }
        public string udmbase { get; set; }
        public decimal cantidad { get; set; }
        public string udmequiv { get; set; }
    }
}