// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class intarifa_complementaria
    {
        public int codtarifa_a { get; set; }
        public int codtarifa_b { get; set; }
    }
}