// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class inzonaalmacen1
    {
        public int codzonaalmacen { get; set; }
        public short fila { get; set; }
        public short columna { get; set; }
    }
}