// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class JEANNIE
    {
        public int? codalmacen { get; set; }
        public int? codvendedor { get; set; }
        public string codcliente { get; set; }
        public string rs { get; set; }
        public string nit { get; set; }
        public decimal? tot_cliente { get; set; }
        public decimal? tot_sinnombre { get; set; }
        public decimal? tot_otros { get; set; }
        public decimal? total { get; set; }
    }
}