// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class JUNIO_
    {
        public double? codpersona { get; set; }
        public double? monto { get; set; }
    }
}