// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class maconcepto_movto
    {
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public bool factor { get; set; }
        public DateTime fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
    }
}