// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class mamovimiento1
    {
        public int? codmovimiento { get; set; }
        public string codmaterial { get; set; }
        public string ud { get; set; }
        public decimal? cantidad { get; set; }
    }
}