// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class otroscon2
    {
        public int? COD { get; set; }
        public DateTime? FECHA { get; set; }
        public string CONOCIMIENTO { get; set; }
    }
}