// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class pcmcalls
    {
        public string RecType { get; set; }
        public int RecNo { get; set; }
        public string CustNo { get; set; }
        public string OrigID { get; set; }
        public string TerID { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Duration { get; set; }
        public string Digits { get; set; }
        public string AccCode { get; set; }
        public string Clid { get; set; }
    }
}