// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class pecargo
    {
        public int codigo { get; set; }
        public int? codanterior { get; set; }
        public string descripcion { get; set; }
        public decimal? salariodesglozado { get; set; }
        public string monedasaldes { get; set; }
        public decimal salariobase { get; set; }
        public string moneda { get; set; }
        public decimal comision { get; set; }
        public string monedacom { get; set; }
        public bool calculahrsextras { get; set; }
        public bool rotativo { get; set; }
        public decimal portiendaarea { get; set; }
        public decimal portiendanac { get; set; }
        public decimal poralmarea { get; set; }
        public decimal poralmnac { get; set; }
        public decimal poralmacen { get; set; }
        public string horareg { get; set; }
        public DateTime? fechareg { get; set; }
        public string usuarioreg { get; set; }
        public string desccorta { get; set; }
        public decimal? porhrsextras { get; set; }
        public bool? habilitado { get; set; }
        public bool? cargo_externo { get; set; }
        public bool? comision_fija { get; set; }
        public int? codrango_comision { get; set; }
        public int? codtramo_comision { get; set; }
        public bool? comision_segun_rango { get; set; }
        public bool? comision_segun_tramo { get; set; }
        public bool? pyme { get; set; }
        public decimal? comision_rendimiento { get; set; }
        public string monedacom_rendimiento { get; set; }
        public int? codnuevo_back { get; set; }
        public decimal? bono_hrs_extras { get; set; }
        public string codmoneda_bono_hrs_extras { get; set; }
        public bool? compuesto { get; set; }
        public decimal? porcen_comision_vta { get; set; }
        public decimal? porcen_comision_rendto { get; set; }
        public decimal? comision_movilidad { get; set; }
        public string monedacom_movilidad { get; set; }
        public decimal? total_ganado_estandar { get; set; }
        public string codmoneda_total_ganado_estandar { get; set; }
    }
}