// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class pecargo1
    {
        public int codigo { get; set; }
        public int codcargo { get; set; }
        public string desc_cargo { get; set; }
        public string desccorta_cargo { get; set; }
        public decimal comision { get; set; }
        public string codmoneda_comision { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
        public string horareg { get; set; }
        public bool? principal { get; set; }
        public decimal? porcentaje { get; set; }
        public decimal? comision_total { get; set; }
    }
}