// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class pecomision4
    {
        public int codplanilla { get; set; }
        public int? codmovto { get; set; }
        public int codpersona { get; set; }
        public int? codcargo { get; set; }
        public decimal? faltas { get; set; }
        public decimal? diastrabajado { get; set; }
        public decimal totalganado { get; set; }
        public decimal? sueldofijo { get; set; }
        public decimal? desctosueldofaltas { get; set; }
        public decimal? totalneto { get; set; }
        public decimal? sabado { get; set; }
        public decimal? bonosabados { get; set; }
        public decimal? sueldocomision { get; set; }
        public decimal? ComAg { get; set; }
        public decimal? ComAMi { get; set; }
        public decimal? ComAMa { get; set; }
        public decimal? ComNMi { get; set; }
        public decimal? ComNMa { get; set; }
        public decimal? comision { get; set; }
        public decimal? desglocecomision { get; set; }
        public decimal? nrohrsextra { get; set; }
        public decimal? valhrsextra { get; set; }
        public decimal? compensamesant { get; set; }
        public decimal? reintegro { get; set; }
        public decimal? desctocomisionfaltas { get; set; }
        public decimal? comtotal { get; set; }
        public decimal? compensatorio { get; set; }
        public decimal? compensamessgte { get; set; }
        public int? codalmacen { get; set; }
        public decimal? porhrsextras { get; set; }
        public decimal? bonosabados_real { get; set; }
        public decimal? bonohrsextrasd8 { get; set; }
        public decimal? nrohrsextra2 { get; set; }
        public decimal? comis_tienda_cba { get; set; }
        public decimal? comis_externo_cba { get; set; }
        public decimal? total_area_cba { get; set; }
        public decimal? comis_tienda_lpz { get; set; }
        public decimal? comis_externo_lpz { get; set; }
        public decimal? total_area_lpz { get; set; }
        public decimal? comis_tienda_scz { get; set; }
        public decimal? comis_externo_scz { get; set; }
        public decimal? total_area_scz { get; set; }
        public decimal? comis_tienda_area { get; set; }
        public decimal? comis_externo_area { get; set; }
        public decimal? total_area { get; set; }
        public decimal? total_descuentos { get; set; }
    }
}