// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class pecomvendedor1
    {
        public int codplanilla { get; set; }
        public int codvendedor { get; set; }
        public int? codpersona { get; set; }
        public int? codmovto { get; set; }
        public int? codcargo { get; set; }
        public string desccargo { get; set; }
        public decimal? comision_liquido { get; set; }
    }
}