// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class peestudio
    {
        public int codper { get; set; }
        public string clase { get; set; }
        public int anos { get; set; }
        public DateTime fechainicio { get; set; }
        public DateTime fechafin { get; set; }
        public string titulo { get; set; }
        public string institucion { get; set; }
        public string lugar { get; set; }
        public string obs { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
    }
}