// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class peindemniza
    {
        public int codigo { get; set; }
        public int mes { get; set; }
        public int anio { get; set; }
        public int? nromeses { get; set; }
        public int? estado { get; set; }
        public string obs { get; set; }
        public bool cerrado { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
    }
}