// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class pemovimiento_inc
    {
        public int codigo { get; set; }
        public int? anio { get; set; }
        public int? mes { get; set; }
        public int? codcargo { get; set; }
        public int? codpersona { get; set; }
        public decimal? salario_base { get; set; }
        public decimal? comision { get; set; }
        public decimal? porcentaje { get; set; }
        public decimal? porcen_inc { get; set; }
    }
}