// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class peplancomision1
    {
        public int codigo { get; set; }
        public int codplancomision { get; set; }
        public int diasde { get; set; }
        public int diasal { get; set; }
        public decimal pesode { get; set; }
        public decimal pesoal { get; set; }
        public string nivel { get; set; }
        public decimal porcentaje { get; set; }
    }
}