// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class peplanporcen1
    {
        public byte codplanporcen { get; set; }
        public short de { get; set; }
        public short a { get; set; }
        public decimal porcentaje { get; set; }
        public decimal porcendesde { get; set; }
        public decimal porcenhasta { get; set; }
    }
}