// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class pepsueldo3
    {
        public int codplanilla { get; set; }
        public int? codalmacen { get; set; }
        public int codpersona { get; set; }
        public decimal? habermensual { get; set; }
        public decimal? bonoantiguedad { get; set; }
        public decimal? bonohrsextras { get; set; }
        public decimal? TotalCotizable { get; set; }
        public decimal? Subsidios { get; set; }
        public decimal? TotalGanado { get; set; }
        public decimal? afp { get; set; }
        public decimal? rciva { get; set; }
        public decimal? TotalDesc { get; set; }
        public decimal? Liquido { get; set; }
    }
}