// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class peptributaria_back1
    {
        public int CodPlanilla { get; set; }
        public int CodPersona { get; set; }
        public int? CodAlmacen { get; set; }
        public decimal HaberNeto { get; set; }
        public decimal MinNoImponible { get; set; }
        public decimal DifSujetaImpuesto { get; set; }
        public decimal IVA { get; set; }
        public decimal RCIVA { get; set; }
        public decimal RegComplementario { get; set; }
        public decimal SaldoMesFisco { get; set; }
        public decimal SaldoMesDep { get; set; }
        public decimal SaldoMesAnt { get; set; }
        public decimal Actualizacion { get; set; }
        public decimal Total { get; set; }
        public decimal SALDOTOTALDEP { get; set; }
        public decimal SaldoUtilizado { get; set; }
        public decimal ImpuestoRetenido { get; set; }
        public decimal SaldoDepMesSig { get; set; }
        public decimal? HaberNeto_Reintegro { get; set; }
    }
}