// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class pereintegro_indemnizacion
    {
        public string anio { get; set; }
        public string mes { get; set; }
        public double? codpersona { get; set; }
        public double? total_cotizable { get; set; }
        public double? total_reintegro { get; set; }
        public string codmoneda { get; set; }
    }
}