// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class pevarvendedor
    {
        public int? codpersona { get; set; }
        public int? anio { get; set; }
        public int? mes { get; set; }
        public int? codvendedor { get; set; }
        public decimal? monto { get; set; }
        public string codmoneda { get; set; }
    }
}