// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class pevacacion
    {
        public int codigo { get; set; }
        public string id { get; set; }
        public int numeroid { get; set; }
        public int almacen { get; set; }
        public int persona { get; set; }
        public DateTime fecha { get; set; }
        public DateTime fechadel { get; set; }
        public DateTime fechaal { get; set; }
        public decimal dias { get; set; }
        public bool mediodia { get; set; }
        public int reemplazante { get; set; }
        public byte tipo { get; set; }
        public string obs { get; set; }
        public bool anulada { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
        public byte? descontardias { get; set; }
    }
}