// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class pevarconcepto
    {
        public int codpersona { get; set; }
        public int codconcepto { get; set; }
        public DateTime desde { get; set; }
        public DateTime hasta { get; set; }
        public bool validez { get; set; }
        public decimal? importe { get; set; }
        public string codmoneda { get; set; }
        public decimal? porcentaje { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
    }
}