// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class prlogprecio1
    {
        public int codplanilla { get; set; }
        public string coditem { get; set; }
        public decimal? PrecioMay { get; set; }
        public decimal? PrecioMay_PZ { get; set; }
        public decimal? PrecioMay_Final { get; set; }
        public decimal? PrecioMM { get; set; }
        public decimal? PrecioMM_PZ { get; set; }
        public decimal? Factor_MM { get; set; }
        public decimal? PrecioMM_MN { get; set; }
        public decimal? PrecioMM_Final { get; set; }
        public decimal? PrecioMin { get; set; }
        public decimal? PrecioMin_PZ { get; set; }
        public decimal? Factor_Min { get; set; }
        public decimal? PrecioMin_MN { get; set; }
        public decimal? PrecioMin_Final { get; set; }
    }
}