// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class promvtasclie
    {
        public int? anio { get; set; }
        public int? mes { get; set; }
        public string codcliente_o { get; set; }
        public decimal? total_us { get; set; }
        public decimal? total_kg { get; set; }
        public int? codalmacen_o { get; set; }
        public int? codalmacen_d { get; set; }
        public int? codvendedor_v { get; set; }
        public int? codvendedor_o { get; set; }
        public int? codvendedor_d { get; set; }
        public string codcliente_d { get; set; }
        public string razonsocial { get; set; }
        public string coddepto { get; set; }
        public bool? movido { get; set; }
    }
}