// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class raz78946
    {
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public decimal? valor_1 { get; set; }
        public decimal? valor_2 { get; set; }
        public decimal? valor_3 { get; set; }
        public decimal? valor_4 { get; set; }
        public decimal? valor_5 { get; set; }
        public decimal? valor_final { get; set; }
    }
}