// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class repeanticiposfc_saldos
    {
        public int codigo { get; set; }
        public int? anio { get; set; }
        public int? mes { get; set; }
    }
}