// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class reporte_cons
    {
        public int? codgrupo { get; set; }
        public string descripcion { get; set; }
        public int? codvendedor { get; set; }
        public string codcliente { get; set; }
        public string razonsocial { get; set; }
        public decimal? US_2010 { get; set; }
        public decimal? KG_2010 { get; set; }
        public decimal? US_1 { get; set; }
        public decimal? KG_1 { get; set; }
        public decimal? US_2 { get; set; }
        public decimal? KG_2 { get; set; }
        public decimal? US_3 { get; set; }
        public decimal? KG_3 { get; set; }
        public decimal? US_4 { get; set; }
        public decimal? KG_4 { get; set; }
        public decimal? US_5 { get; set; }
        public decimal? KG_5 { get; set; }
        public decimal? US_6 { get; set; }
        public decimal? KG_6 { get; set; }
        public decimal? US_7 { get; set; }
        public decimal? KG_7 { get; set; }
        public decimal? US_8 { get; set; }
        public decimal? KG_8 { get; set; }
        public decimal? US_9 { get; set; }
        public decimal? KG_9 { get; set; }
        public decimal? total_cliente { get; set; }
        public decimal? total_cliente_kg { get; set; }
    }
}