// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class reporte
    {
        public int? codvendedor { get; set; }
        public int? mes { get; set; }
        public string nombremes { get; set; }
        public string tipo { get; set; }
        public decimal? total { get; set; }
    }
}