// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class reporterc2
    {
        public int? codcuota { get; set; }
        public int? codigo { get; set; }
        public int? codalmacen { get; set; }
        public string id { get; set; }
        public int? numeroid { get; set; }
        public DateTime? fecha { get; set; }
        public int? nrocuota { get; set; }
        public DateTime? fecha_venc { get; set; }
        public DateTime? fecha_pago { get; set; }
        public decimal? dias { get; set; }
    }
}