// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class rutas411_
    {
        public double? codvendedor { get; set; }
        public double? codcliente { get; set; }
        public string Rason_social_ { get; set; }
        public string Nombre_comercial { get; set; }
        public double? latitud { get; set; }
        public double? longitud { get; set; }
        public string ruta { get; set; }
        public string ruta1 { get; set; }
        public string ruta2 { get; set; }
        public string ruta3 { get; set; }
    }
}