// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class slrecategorizacion
    {
        public int codigo { get; set; }
        public DateTime? fechasolicitud { get; set; }
        public int? codpersona { get; set; }
        public DateTime? fechaing { get; set; }
        public string cargoactual { get; set; }
        public DateTime? fecha_urecat { get; set; }
        public string sueldo { get; set; }
        public string comision { get; set; }
        public string propuesta { get; set; }
        public string desdemes { get; set; }
        public string desdeanio { get; set; }
        public string sueldop { get; set; }
        public string comisionp { get; set; }
        public string obs { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
    }
}