// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class temporal
    {
        public int? codalmacen { get; set; }
        public int? codvendedor { get; set; }
        public string coditem { get; set; }
        public decimal? cantidad { get; set; }
        public decimal? monto { get; set; }
        public decimal? saldofinal { get; set; }
        public decimal? traspaso { get; set; }
    }
}