// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class temp_DTDM_monto_pagado_240
    {
        public int? coddocumento { get; set; }
        public DateTime? fecha { get; set; }
        public int? codcobranza { get; set; }
        public decimal? total { get; set; }
    }
}