// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class tempo_mm
    {
        public string codigo { get; set; }
        public decimal? total { get; set; }
    }
}