// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class temp_esaldoanticipo680
    {
        public int? delperiodo { get; set; }
        public int? codanticipo { get; set; }
        public int? tipo { get; set; }
        public string id { get; set; }
        public int? numeroid { get; set; }
        public string codcliente { get; set; }
        public bool? vtacontado { get; set; }
        public DateTime? fecha { get; set; }
        public string codmoneda { get; set; }
        public decimal? monto { get; set; }
        public decimal? dev_anterior { get; set; }
        public decimal? montopagado { get; set; }
        public decimal? saldo_anterior { get; set; }
        public decimal? anticipo { get; set; }
        public decimal? dev_anticipo { get; set; }
        public decimal? reversion { get; set; }
        public decimal? reversion_contado { get; set; }
        public decimal? saldo_periodo { get; set; }
        public decimal? saldo_final { get; set; }
        public decimal? monto_revertido_prof { get; set; }
        public decimal? montopagado_contado { get; set; }
        public decimal? montopagado_contado_anterior { get; set; }
        public decimal? monto_revertido_prof_anterior { get; set; }
        public bool? paraventa_contado { get; set; }
        public decimal? monto_revertido_una_prof_anterior { get; set; }
    }
}