// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class temp_auditnc
    {
        public int codnc { get; set; }
        public string id { get; set; }
        public int numeroid { get; set; }
        public DateTime fecha { get; set; }
        public int? codfactura { get; set; }
        public string idfc { get; set; }
        public int? nroid_fc { get; set; }
        public DateTime fecha_fc { get; set; }
        public decimal? ttl_fc { get; set; }
        public decimal subtotal { get; set; }
        public decimal credito { get; set; }
        public decimal total { get; set; }
        public int? codremision { get; set; }
        public string idnr { get; set; }
        public int? nroid_nr { get; set; }
        public DateTime? fecha_nr { get; set; }
        public decimal? ttl_nr { get; set; }
    }
}