// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class temp_listaclie_esaldosfc_423_504_3_540_650_819_759_449_961_628
    {
        public string cambio { get; set; }
        public int? tipo { get; set; }
        public int antes { get; set; }
        public string codcliente { get; set; }
        public string razonsocial { get; set; }
        public int codalmacen { get; set; }
        public string tipo_saldo { get; set; }
    }
}