// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class temp_veventas_dia_829
    {
        public bool actualizar { get; set; }
        public int codfactura { get; set; }
        public int codremision { get; set; }
        public int codalmacen { get; set; }
        public int codvendedor { get; set; }
        public bool anulada { get; set; }
        public string nulo { get; set; }
        public byte tipopago { get; set; }
        public string tipo_pago { get; set; }
        public decimal? desc_pp { get; set; }
        public string id { get; set; }
        public int numeroid { get; set; }
        public string coddepto { get; set; }
        public string codcliente { get; set; }
        public DateTime fecha { get; set; }
        public int? anio { get; set; }
        public int? mes { get; set; }
        public int? dia { get; set; }
        public string dia_semana { get; set; }
        public int? semana { get; set; }
        public string hora { get; set; }
        public string minuto { get; set; }
        public decimal total_mb { get; set; }
        public string codmoneda { get; set; }
        public decimal? factorme { get; set; }
        public decimal? total_me { get; set; }
        public decimal? venta_kg { get; set; }
        public int nro_fichas { get; set; }
        public int nroitems { get; set; }
    }
}