// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class TEMPORALUNIDO
    {
        public int? codalmacen { get; set; }
        public int? codvendedor { get; set; }
        public string coditem { get; set; }
        public decimal? cantidad { get; set; }
        public decimal? monto { get; set; }
        public decimal? saldofinal { get; set; }
        public decimal? traspaso { get; set; }
        public int? codalmacen1 { get; set; }
        public int? codvendedor1 { get; set; }
        public string coditem1 { get; set; }
        public decimal? cantidad1 { get; set; }
        public decimal? monto1 { get; set; }
        public decimal? saldofinal1 { get; set; }
        public decimal? traspaso1 { get; set; }
        public int? codalmacen2 { get; set; }
        public int? codvendedor2 { get; set; }
        public string coditem2 { get; set; }
        public decimal? cantidad2 { get; set; }
        public decimal? monto2 { get; set; }
        public decimal? saldofinal2 { get; set; }
        public decimal? traspaso2 { get; set; }
        public int? codalmacen3 { get; set; }
        public int? codvendedor3 { get; set; }
        public string coditem3 { get; set; }
        public decimal? cantidad3 { get; set; }
        public decimal? monto3 { get; set; }
        public decimal? saldofinal3 { get; set; }
        public decimal? traspaso3 { get; set; }
        public int? codalmacen4 { get; set; }
        public int? codvendedor4 { get; set; }
        public string coditem4 { get; set; }
        public decimal? cantidad4 { get; set; }
        public decimal? monto4 { get; set; }
        public decimal? saldofinal4 { get; set; }
        public decimal? traspaso4 { get; set; }
        public int? codalmacen5 { get; set; }
        public int? codvendedor5 { get; set; }
        public string coditem5 { get; set; }
        public decimal? cantidad5 { get; set; }
        public decimal? monto5 { get; set; }
        public decimal? saldofinal5 { get; set; }
        public decimal? traspaso5 { get; set; }
        public int? codalmacen6 { get; set; }
        public int? codvendedor6 { get; set; }
        public string coditem6 { get; set; }
        public decimal? cantidad6 { get; set; }
        public decimal? monto6 { get; set; }
        public decimal? saldofinal6 { get; set; }
        public decimal? traspaso6 { get; set; }
        public int? codalmacen7 { get; set; }
        public int? codvendedor7 { get; set; }
        public string coditem7 { get; set; }
        public decimal? cantidad7 { get; set; }
        public decimal? monto7 { get; set; }
        public decimal? saldofinal7 { get; set; }
        public decimal? traspaso7 { get; set; }
    }
}