// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class tp_80860
    {
        public string tipo { get; set; }
        public int? codremision { get; set; }
        public string codcliente { get; set; }
        public string razonsocial { get; set; }
        public string clasificacion { get; set; }
        public decimal? total_remision { get; set; }
        public decimal? peso_remision { get; set; }
        public string preparacion { get; set; }
        public int? nro_items { get; set; }
        public string id_proforma { get; set; }
        public int? numeroid_proforma { get; set; }
        public DateTime? fecha_proforma { get; set; }
        public decimal? peso_proforma { get; set; }
        public string id_remision { get; set; }
        public int? numeroid_remision { get; set; }
        public DateTime? fecha_remision { get; set; }
        public string horareg_remision { get; set; }
        public string id_factura { get; set; }
        public int? numeroid_factura { get; set; }
        public decimal? dias { get; set; }
        public decimal? horas { get; set; }
        public DateTime? fecha_inicial { get; set; }
        public string hora_inicial { get; set; }
        public int? hini { get; set; }
        public int? mini { get; set; }
        public DateTime? fechaaut_proforma { get; set; }
        public string horaaut_proforma { get; set; }
        public int? haut { get; set; }
        public int? maut { get; set; }
        public DateTime? fecha_empieza_preparacion { get; set; }
        public string hora_empieza_preparacion { get; set; }
        public int? h_emp { get; set; }
        public int? m_emp { get; set; }
        public DateTime? fecha_factura { get; set; }
        public string horareg_factura { get; set; }
        public int? h { get; set; }
        public int? m { get; set; }
        public DateTime? fdespachado { get; set; }
        public string hdespachado { get; set; }
        public int? hdesp { get; set; }
        public int? mdesp { get; set; }
        public decimal? horas_toma { get; set; }
        public decimal? horas_espera { get; set; }
        public decimal? horas_preparacion { get; set; }
        public decimal? horas_entrega { get; set; }
        public decimal? horas_toma_no_habiles { get; set; }
        public decimal? horas_espera_no_habiles { get; set; }
        public decimal? horas_preparacion_no_habiles { get; set; }
        public decimal? horas_entrega_no_habiles { get; set; }
        public decimal? horas_toma_total { get; set; }
        public decimal? horas_espera_total { get; set; }
        public decimal? horas_preparacion_total { get; set; }
        public decimal? horas_entrega_total { get; set; }
        public int? codproforma { get; set; }
    }
}