// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class vecalculoprecios1
    {
        public int? codcalculoprecios { get; set; }
        public string coditem_original { get; set; }
        public string coditem { get; set; }
        public string descripcion { get; set; }
        public string medida { get; set; }
        public decimal? inicial { get; set; }
        public decimal? x_factor { get; set; }
        public decimal? procesado { get; set; }
        public decimal? final { get; set; }
        public decimal? anterior { get; set; }
    }
}