// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class vecalccomisionista2
    {
        public int codplanilla { get; set; }
        public string codvendedor { get; set; }
        public decimal? estandar { get; set; }
        public decimal? porcenmin { get; set; }
        public decimal? minimo { get; set; }
        public decimal? ti { get; set; }
        public decimal? recutotal { get; set; }
        public decimal? recutotalimp { get; set; }
        public decimal? montocomision { get; set; }
        public decimal? total_desctos { get; set; }
        public decimal? total { get; set; }
        public decimal? salario_basico { get; set; }
        public decimal? haber_mensual { get; set; }
        public decimal? dias_trabajado { get; set; }
        public int? codmovto { get; set; }
        public decimal? porcentaje_logrado { get; set; }
        public decimal? comision_segun_porcentaje { get; set; }
        public decimal? descto_segun_porcentaje { get; set; }
        public decimal? devolucion_mora { get; set; }
        public decimal? objkg_est_act { get; set; }
        public decimal? ventaspeso { get; set; }
        public decimal? porcen_logrado_seg_rango { get; set; }
        public decimal? ttl_ganado_est { get; set; }
        public string mon_ttlge { get; set; }
        public decimal? porcen_vta_kg_logrado { get; set; }
        public decimal? total_ganado { get; set; }
        public decimal? comision_rendimiento { get; set; }
        public decimal? comision_movilidad { get; set; }
        public decimal? descto_rendimiento_movilidad { get; set; }
    }
}