// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class vecbzaexcluida
    {
        public int anio { get; set; }
        public byte mes { get; set; }
        public string id { get; set; }
        public string nroid { get; set; }
        public decimal? totaldist { get; set; }
        public string obs { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
        public int? codalmacen { get; set; }
        public int? codvendedor { get; set; }
        public string estienda { get; set; }
    }
}