// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class vecenso1
    {
        public int codigo { get; set; }
        public int? codcenso { get; set; }
        public string hora { get; set; }
        public string minuto { get; set; }
        public string nombre_negocio { get; set; }
        public string nombre_cliente { get; set; }
        public string direccion { get; set; }
        public string telefonos { get; set; }
        public string tipo { get; set; }
        public bool? comercia { get; set; }
        public int? no_comercia_razon { get; set; }
        public string quien_lo_atiende { get; set; }
        public bool? compra_pertec { get; set; }
        public bool? compra_pstck { get; set; }
        public bool? compra_pstck_g2 { get; set; }
        public bool? compra_pstck_g5 { get; set; }
        public bool? compra_pstck_g8 { get; set; }
        public bool? compra_pstck_chip { get; set; }
        public bool? compra_pstck_maq { get; set; }
        public bool? compra_pstck_vari { get; set; }
        public bool? compra_pstck_tech { get; set; }
        public bool? compra_pstck_aran { get; set; }
        public bool? compra_pstck_auto { get; set; }
        public int? compra_pstck_porque { get; set; }
        public bool? compra_grado5 { get; set; }
        public bool? compra_grado5_g2 { get; set; }
        public bool? compra_grado5_g5 { get; set; }
        public bool? compra_grado5_g8 { get; set; }
        public bool? compra_grado5_chip { get; set; }
        public bool? compra_grado5_maq { get; set; }
        public bool? compra_grado5_vari { get; set; }
        public bool? compra_grado5_tech { get; set; }
        public bool? compra_grado5_aran { get; set; }
        public bool? compra_grado5_auto { get; set; }
        public int? compra_grado5_porque { get; set; }
        public bool? compra_perbol { get; set; }
        public bool? compra_perbol_g2 { get; set; }
        public bool? compra_perbol_g5 { get; set; }
        public bool? compra_perbol_g8 { get; set; }
        public bool? compra_perbol_chip { get; set; }
        public bool? compra_perbol_maq { get; set; }
        public bool? compra_perbol_vari { get; set; }
        public bool? compra_perbol_tech { get; set; }
        public bool? compra_perbol_aran { get; set; }
        public bool? compra_perbol_auto { get; set; }
        public int? compra_perbol_porque { get; set; }
        public bool? compra_otro { get; set; }
        public string compra_otro_descripcion { get; set; }
        public bool? compra_otro_g2 { get; set; }
        public bool? compra_otro_g5 { get; set; }
        public bool? compra_otro_g8 { get; set; }
        public bool? compra_otro_chip { get; set; }
        public bool? compra_otro_maq { get; set; }
        public bool? compra_otro_vari { get; set; }
        public bool? compra_otro_tech { get; set; }
        public bool? compra_otro_aran { get; set; }
        public bool? compra_otro_auto { get; set; }
        public int? compra_otro_porque { get; set; }
        public string observaciones { get; set; }
        public string telefonos2 { get; set; }
        public string celular { get; set; }
        public string celular2 { get; set; }
        public string nombre_vendedor { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
    }
}