// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class vecliente_dpto
    {
        public string codcliente_o { get; set; }
        public string codcliente_d { get; set; }
        public int? codalmacen_o { get; set; }
        public int? codalmacen_d { get; set; }
        public int? codvendedor_act { get; set; }
        public int? codvendedor_o { get; set; }
        public int? codvendedor_d { get; set; }
        public string cliente { get; set; }
        public string razonsocial { get; set; }
        public string ciu { get; set; }
        public string coddepto { get; set; }
        public string codprov { get; set; }
        public string descprov { get; set; }
        public string codrubro { get; set; }
        public string descrubro { get; set; }
        public string clasificacion { get; set; }
        public int? codptovta { get; set; }
        public string descptovta { get; set; }
        public DateTime? fechaactualiza { get; set; }
        public string hractualiza { get; set; }
        public bool? movido { get; set; }
        public bool? nuevo { get; set; }
        public string razonsocial_padre { get; set; }
        public string direccion { get; set; }
        public string telefono1 { get; set; }
        public string celular1 { get; set; }
        public string celular2 { get; set; }
        public string nombtitular { get; set; }
        public string telefono2 { get; set; }
        public int? codtienda { get; set; }
        public string codcliente_a { get; set; }
        public string codcliente_b { get; set; }
    }
}