// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class veclientesiguales_antiguos
    {
        public string codcliente_a { get; set; }
        public string codcliente_b { get; set; }
        public string cliente_antiguo { get; set; }
    }
}