// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class vedescuento1
    {
        public int codigo { get; set; }
        public int coddescuento { get; set; }
        public string codlinea { get; set; }
        public decimal descuento { get; set; }
    }
}