// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class vedesitem_log_aut
    {
        public DateTime? fecha { get; set; }
        public string codcliente { get; set; }
        public string id { get; set; }
        public int? numeroid { get; set; }
        public string tipo { get; set; }
        public string codigo { get; set; }
        public string nivel { get; set; }
        public string usuario { get; set; }
        public string hora { get; set; }
        public int? codalmacen { get; set; }
        public string modalidad { get; set; }
    }
}