// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class vedesextra_item
    {
        public int? coddesextra { get; set; }
        public string coditem { get; set; }
        public decimal? porcentaje { get; set; }
    }
}