// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class vedespacho2
    {
        public int coddespacho { get; set; }
        public string motivo { get; set; }
        public string obs { get; set; }
        public DateTime? fdespachado { get; set; }
        public string hdespachado { get; set; }
        public int? resdespacho { get; set; }
        public DateTime fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
    }
}