// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class vehojaderuta
    {
        public int codigo { get; set; }
        public int? codalmacen { get; set; }
        public int? codvendedor { get; set; }
        public DateTime? fecha { get; set; }
        public decimal? obj_venta { get; set; }
        public decimal? v_real { get; set; }
        public decimal? porcen_us { get; set; }
        public decimal? obj_venta_kg { get; set; }
        public decimal? v_real_kg { get; set; }
        public decimal? porcen_kg { get; set; }
        public decimal? obj_cobranza { get; set; }
        public decimal? c_real { get; set; }
        public decimal? porcen_cob { get; set; }
        public decimal? obj_cobertura { get; set; }
        public decimal? real_cobertura { get; set; }
        public decimal? porcen_cobertura { get; set; }
        public decimal? obj_efectividad_visita { get; set; }
        public decimal? real_efectividad_visita { get; set; }
        public decimal? porcen_efectividad_visita { get; set; }
        public decimal? obj_efectividad_cob { get; set; }
        public decimal? real_efectividad_cob { get; set; }
        public decimal? porcen_efectividad_cob { get; set; }
        public string plan_venta { get; set; }
        public string plan_cobranza { get; set; }
        public string plan_kg { get; set; }
        public string plan_cobertura { get; set; }
        public string plan_efectividad_visita { get; set; }
        public string plan_efectividad_cob { get; set; }
        public string codruta { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
        public string observacion { get; set; }
        public string observacion_sup { get; set; }
    }
}