// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class vehojaderuta_recordatorio
    {
        public int codigo { get; set; }
        public int? codhojaderuta { get; set; }
        public DateTime? fecha { get; set; }
        public string recordatorio { get; set; }
    }
}