// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class veiva
    {
        public int codigo { get; set; }
        public decimal porcentaje { get; set; }
        public string afip_codigo { get; set; }
    }
}