// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class venombrenit2
    {
        public string codcliente { get; set; }
        public string nombre { get; set; }
        public string nit { get; set; }
        public DateTime fecha { get; set; }
        public bool vigente { get; set; }
        public bool? impdatos { get; set; }
    }
}