// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class vepenal
    {
        public string codcliente { get; set; }
        public int? codgrupo { get; set; }
        public int? tiempo { get; set; }
    }
}