// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class veproforma_valida
    {
        public int codproforma { get; set; }
        public string codcontrol { get; set; }
        public int? nroitems { get; set; }
        public string nit { get; set; }
        public decimal? subtotal { get; set; }
        public decimal? descuentos { get; set; }
        public decimal? recargos { get; set; }
        public decimal? total { get; set; }
        public string valido { get; set; }
        public string observacion { get; set; }
        public string obsdetalle { get; set; }
        public int? codservicio { get; set; }
        public string datoa { get; set; }
        public string datob { get; set; }
        public string clave_servicio { get; set; }
    }
}