// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class verecumayoristas
    {
        public string id { get; set; }
        public int? numeroid { get; set; }
        public string codvendedor { get; set; }
        public int codcomisiones { get; set; }
        public decimal cantidad { get; set; }
        public string coditem { get; set; }
        public string codlinea { get; set; }
        public int codgrupomer { get; set; }
        public string niveldesc { get; set; }
        public decimal peso { get; set; }
        public int dias { get; set; }
        public int? dedias { get; set; }
        public int? adias { get; set; }
        public decimal porcen_dist { get; set; }
        public decimal monto_dist { get; set; }
        public decimal iva_monto_dist { get; set; }
        public decimal por_comision { get; set; }
        public decimal comision { get; set; }
        public decimal? desctocomision { get; set; }
        public bool? item_excluido { get; set; }
        public decimal? monto_dist_aux { get; set; }
        public string CODCLIENTE { get; set; }
        public int? CODPTOVTA { get; set; }
        public decimal? POR_COMISION_INC { get; set; }
        public int? codcobranza { get; set; }
    }
}