// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class veticketnota
    {
        public int? codalmacen { get; set; }
        public DateTime? fecha { get; set; }
        public string hora { get; set; }
        public string nroticket { get; set; }
        public string nota { get; set; }
    }
}