// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class vetipo_comprobante
    {
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public string horareg { get; set; }
        public DateTime? fechareg { get; set; }
        public string usuarioreg { get; set; }
        public byte lv_suma { get; set; }
        public byte lc_suma { get; set; }
        public string tipo { get; set; }
    }
}