// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class veventasalm_nc
    {
        public int anio { get; set; }
        public int mes { get; set; }
        public string id { get; set; }
        public int numeroid { get; set; }
        public DateTime fecha { get; set; }
        public string codcliente { get; set; }
        public decimal? total_credito { get; set; }
        public string codmoneda { get; set; }
        public decimal? peso_credito { get; set; }
    }
}