// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class veventas_cliente_mercaderia
    {
        public string codcliente { get; set; }
        public int? anio { get; set; }
        public string codmercaderia { get; set; }
        public decimal? prom_mes_us { get; set; }
        public decimal? prom_mes_kg { get; set; }
        public string tipo { get; set; }
    }
}