// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIAW.Models
{
    public partial class wb_sl_listaextension
    {
        public int codigo { get; set; }
        public string id { get; set; }
        public int? numeroid { get; set; }
        public string obs { get; set; }
        public string tipo { get; set; }
        public int? dias { get; set; }
        public DateTime? fechareg { get; set; }
    }
}