//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class facturaElectronicaCompraVentaBon {
    
    private facturaElectronicaCompraVentaBonCabecera cabeceraField;
    
    private facturaElectronicaCompraVentaBonDetalle[] detalleField;
    
    private Signature signatureField;
    
    /// <remarks/>
    public facturaElectronicaCompraVentaBonCabecera cabecera {
        get {
            return this.cabeceraField;
        }
        set {
            this.cabeceraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("detalle")]
    public facturaElectronicaCompraVentaBonDetalle[] detalle {
        get {
            return this.detalleField;
        }
        set {
            this.detalleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public Signature Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class facturaElectronicaCompraVentaBonCabecera {
    
    private string nitEmisorField;
    
    private string razonSocialEmisorField;
    
    private string municipioField;
    
    private string telefonoField;
    
    private string numeroFacturaField;
    
    private string cufField;
    
    private string cufdField;
    
    private string codigoSucursalField;
    
    private string direccionField;
    
    private string codigoPuntoVentaField;
    
    private System.DateTime fechaEmisionField;
    
    private string nombreRazonSocialField;
    
    private string codigoTipoDocumentoIdentidadField;
    
    private string numeroDocumentoField;
    
    private string complementoField;
    
    private string codigoClienteField;
    
    private string codigoMetodoPagoField;
    
    private string numeroTarjetaField;
    
    private decimal montoTotalField;
    
    private decimal montoTotalSujetoIvaField;
    
    private string codigoMonedaField;
    
    private decimal tipoCambioField;
    
    private decimal montoTotalMonedaField;
    
    private System.Nullable<decimal> montoGiftCardField;
    
    private System.Nullable<decimal> descuentoAdicionalField;
    
    private string codigoExcepcionField;
    
    private string cafcField;
    
    private string leyendaField;
    
    private string usuarioField;
    
    private string codigoDocumentoSectorField;
    
    public facturaElectronicaCompraVentaBonCabecera() {
        this.codigoDocumentoSectorField = "35";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string nitEmisor {
        get {
            return this.nitEmisorField;
        }
        set {
            this.nitEmisorField = value;
        }
    }
    
    /// <remarks/>
    public string razonSocialEmisor {
        get {
            return this.razonSocialEmisorField;
        }
        set {
            this.razonSocialEmisorField = value;
        }
    }
    
    /// <remarks/>
    public string municipio {
        get {
            return this.municipioField;
        }
        set {
            this.municipioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string telefono {
        get {
            return this.telefonoField;
        }
        set {
            this.telefonoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string numeroFactura {
        get {
            return this.numeroFacturaField;
        }
        set {
            this.numeroFacturaField = value;
        }
    }
    
    /// <remarks/>
    public string cuf {
        get {
            return this.cufField;
        }
        set {
            this.cufField = value;
        }
    }
    
    /// <remarks/>
    public string cufd {
        get {
            return this.cufdField;
        }
        set {
            this.cufdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codigoSucursal {
        get {
            return this.codigoSucursalField;
        }
        set {
            this.codigoSucursalField = value;
        }
    }
    
    /// <remarks/>
    public string direccion {
        get {
            return this.direccionField;
        }
        set {
            this.direccionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string codigoPuntoVenta {
        get {
            return this.codigoPuntoVentaField;
        }
        set {
            this.codigoPuntoVentaField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime fechaEmision {
        get {
            return this.fechaEmisionField;
        }
        set {
            this.fechaEmisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string nombreRazonSocial {
        get {
            return this.nombreRazonSocialField;
        }
        set {
            this.nombreRazonSocialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codigoTipoDocumentoIdentidad {
        get {
            return this.codigoTipoDocumentoIdentidadField;
        }
        set {
            this.codigoTipoDocumentoIdentidadField = value;
        }
    }
    
    /// <remarks/>
    public string numeroDocumento {
        get {
            return this.numeroDocumentoField;
        }
        set {
            this.numeroDocumentoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string complemento {
        get {
            return this.complementoField;
        }
        set {
            this.complementoField = value;
        }
    }
    
    /// <remarks/>
    public string codigoCliente {
        get {
            return this.codigoClienteField;
        }
        set {
            this.codigoClienteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codigoMetodoPago {
        get {
            return this.codigoMetodoPagoField;
        }
        set {
            this.codigoMetodoPagoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string numeroTarjeta {
        get {
            return this.numeroTarjetaField;
        }
        set {
            this.numeroTarjetaField = value;
        }
    }
    
    /// <remarks/>
    public decimal montoTotal {
        get {
            return this.montoTotalField;
        }
        set {
            this.montoTotalField = value;
        }
    }
    
    /// <remarks/>
    public decimal montoTotalSujetoIva {
        get {
            return this.montoTotalSujetoIvaField;
        }
        set {
            this.montoTotalSujetoIvaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codigoMoneda {
        get {
            return this.codigoMonedaField;
        }
        set {
            this.codigoMonedaField = value;
        }
    }
    
    /// <remarks/>
    public decimal tipoCambio {
        get {
            return this.tipoCambioField;
        }
        set {
            this.tipoCambioField = value;
        }
    }
    
    /// <remarks/>
    public decimal montoTotalMoneda {
        get {
            return this.montoTotalMonedaField;
        }
        set {
            this.montoTotalMonedaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> montoGiftCard {
        get {
            return this.montoGiftCardField;
        }
        set {
            this.montoGiftCardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> descuentoAdicional {
        get {
            return this.descuentoAdicionalField;
        }
        set {
            this.descuentoAdicionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string codigoExcepcion {
        get {
            return this.codigoExcepcionField;
        }
        set {
            this.codigoExcepcionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string cafc {
        get {
            return this.cafcField;
        }
        set {
            this.cafcField = value;
        }
    }
    
    /// <remarks/>
    public string leyenda {
        get {
            return this.leyendaField;
        }
        set {
            this.leyendaField = value;
        }
    }
    
    /// <remarks/>
    public string usuario {
        get {
            return this.usuarioField;
        }
        set {
            this.usuarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codigoDocumentoSector {
        get {
            return this.codigoDocumentoSectorField;
        }
        set {
            this.codigoDocumentoSectorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class facturaElectronicaCompraVentaBonDetalle {
    
    private string actividadEconomicaField;
    
    private string codigoProductoSinField;
    
    private string codigoProductoField;
    
    private string descripcionField;
    
    private decimal cantidadField;
    
    private string unidadMedidaField;
    
    private decimal precioUnitarioField;
    
    private System.Nullable<decimal> montoDescuentoField;
    
    private decimal subTotalField;
    
    private string numeroSerieField;
    
    private string numeroImeiField;
    
    /// <remarks/>
    public string actividadEconomica {
        get {
            return this.actividadEconomicaField;
        }
        set {
            this.actividadEconomicaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codigoProductoSin {
        get {
            return this.codigoProductoSinField;
        }
        set {
            this.codigoProductoSinField = value;
        }
    }
    
    /// <remarks/>
    public string codigoProducto {
        get {
            return this.codigoProductoField;
        }
        set {
            this.codigoProductoField = value;
        }
    }
    
    /// <remarks/>
    public string descripcion {
        get {
            return this.descripcionField;
        }
        set {
            this.descripcionField = value;
        }
    }
    
    /// <remarks/>
    public decimal cantidad {
        get {
            return this.cantidadField;
        }
        set {
            this.cantidadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string unidadMedida {
        get {
            return this.unidadMedidaField;
        }
        set {
            this.unidadMedidaField = value;
        }
    }
    
    /// <remarks/>
    public decimal precioUnitario {
        get {
            return this.precioUnitarioField;
        }
        set {
            this.precioUnitarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> montoDescuento {
        get {
            return this.montoDescuentoField;
        }
        set {
            this.montoDescuentoField = value;
        }
    }
    
    /// <remarks/>
    public decimal subTotal {
        get {
            return this.subTotalField;
        }
        set {
            this.subTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string numeroSerie {
        get {
            return this.numeroSerieField;
        }
        set {
            this.numeroSerieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string numeroImei {
        get {
            return this.numeroImeiField;
        }
        set {
            this.numeroImeiField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
public partial class Signature {
    
    private SignatureSignedInfo signedInfoField;
    
    private string signatureValueField;
    
    private SignatureKeyInfo keyInfoField;
    
    /// <remarks/>
    public SignatureSignedInfo SignedInfo {
        get {
            return this.signedInfoField;
        }
        set {
            this.signedInfoField = value;
        }
    }
    
    /// <remarks/>
    public string SignatureValue {
        get {
            return this.signatureValueField;
        }
        set {
            this.signatureValueField = value;
        }
    }
    
    /// <remarks/>
    public SignatureKeyInfo KeyInfo {
        get {
            return this.keyInfoField;
        }
        set {
            this.keyInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureSignedInfo {
    
    private SignatureSignedInfoCanonicalizationMethod canonicalizationMethodField;
    
    private SignatureSignedInfoSignatureMethod signatureMethodField;
    
    private SignatureSignedInfoReference referenceField;
    
    /// <remarks/>
    public SignatureSignedInfoCanonicalizationMethod CanonicalizationMethod {
        get {
            return this.canonicalizationMethodField;
        }
        set {
            this.canonicalizationMethodField = value;
        }
    }
    
    /// <remarks/>
    public SignatureSignedInfoSignatureMethod SignatureMethod {
        get {
            return this.signatureMethodField;
        }
        set {
            this.signatureMethodField = value;
        }
    }
    
    /// <remarks/>
    public SignatureSignedInfoReference Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureSignedInfoCanonicalizationMethod {
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureSignedInfoSignatureMethod {
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureSignedInfoReference {
    
    private SignatureSignedInfoReferenceTransform[] transformsField;
    
    private SignatureSignedInfoReferenceDigestMethod digestMethodField;
    
    private string digestValueField;
    
    private string uRIField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
    public SignatureSignedInfoReferenceTransform[] Transforms {
        get {
            return this.transformsField;
        }
        set {
            this.transformsField = value;
        }
    }
    
    /// <remarks/>
    public SignatureSignedInfoReferenceDigestMethod DigestMethod {
        get {
            return this.digestMethodField;
        }
        set {
            this.digestMethodField = value;
        }
    }
    
    /// <remarks/>
    public string DigestValue {
        get {
            return this.digestValueField;
        }
        set {
            this.digestValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string URI {
        get {
            return this.uRIField;
        }
        set {
            this.uRIField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureSignedInfoReferenceTransform {
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureSignedInfoReferenceDigestMethod {
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureKeyInfo {
    
    private SignatureKeyInfoX509Data x509DataField;
    
    /// <remarks/>
    public SignatureKeyInfoX509Data X509Data {
        get {
            return this.x509DataField;
        }
        set {
            this.x509DataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureKeyInfoX509Data {
    
    private string x509CertificateField;
    
    /// <remarks/>
    public string X509Certificate {
        get {
            return this.x509CertificateField;
        }
        set {
            this.x509CertificateField = value;
        }
    }
}
