// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class acmantenimiento
    {
        public int codigo { get; set; }
        public DateTime fecha { get; set; }
        public string observacion { get; set; }
        public decimal monto { get; set; }
        public string moneda { get; set; }
        public int codactivo { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
    }
}