// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class Actual22396
    {
        public string coditem { get; set; }
        public decimal? cantidad { get; set; }
        public decimal? proformas { get; set; }
    }
}