// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class adaudit_creditos
    {
        public string codcliente { get; set; }
        public decimal credito { get; set; }
        public DateTime fecha { get; set; }
        public string codtipocredito { get; set; }
        public string codmoneda { get; set; }
    }
}