// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class adaudit_visitas_clipuntos
    {
        public string codcliente { get; set; }
        public int? diasvisita { get; set; }
        public int? diasventa { get; set; }
    }
}