// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class adaudit_compraslinea431
    {
        public string codcliente { get; set; }
        public int? codgrupo { get; set; }
        public decimal? Acantidad { get; set; }
        public decimal? Atotal { get; set; }
        public decimal? Apromedio { get; set; }
        public string Anivelsis { get; set; }
        public string Anivelpos { get; set; }
        public decimal? Bcantidad { get; set; }
        public decimal? Btotal { get; set; }
        public decimal? Bpromedio { get; set; }
        public string Bnivelsis { get; set; }
        public string Bnivelpos { get; set; }
        public decimal? Ccantidad { get; set; }
        public decimal? Ctotal { get; set; }
        public decimal? Cpromedio { get; set; }
        public string Cnivelsis { get; set; }
        public string Cnivelpos { get; set; }
        public int? codvendedor { get; set; }
        public string codalmacen { get; set; }
        public decimal? porcenc { get; set; }
        public decimal? prom8 { get; set; }
        public string nivel8 { get; set; }
        public decimal? porcen8 { get; set; }
        public string nivelf { get; set; }
        public decimal? porcenf { get; set; }
        public string nivel12 { get; set; }
        public decimal? prom12 { get; set; }
        public decimal? nive_porcen { get; set; }
        public decimal? nivd_porcen { get; set; }
        public decimal? nivc_porcen { get; set; }
        public decimal? nivb_porcen { get; set; }
        public decimal? niva_porcen { get; set; }
        public decimal? nivz_porcen { get; set; }
        public decimal? nivd_hasta { get; set; }
        public decimal? nivc_hasta { get; set; }
        public decimal? nivb_hasta { get; set; }
        public decimal? niva_hasta { get; set; }
        public decimal? nivz_hasta { get; set; }
    }
}