// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class adautorizacion
    {
        public int codigo { get; set; }
        public short nivel { get; set; }
        public string password { get; set; }
        public DateTime vencimiento { get; set; }
        public string obs { get; set; }
        public string codempresa { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
        public int? codpersona { get; set; }
    }
}