// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class adcontacto
    {
        public int codigo { get; set; }
        public string nombre_comercial { get; set; }
        public string nombre_contacto { get; set; }
        public int? tipo { get; set; }
        public string coddepto { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string telefono3 { get; set; }
        public string celular1 { get; set; }
        public string celular2 { get; set; }
        public string celular3 { get; set; }
    }
}