// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class adservicio
    {
        public int codigo { get; set; }
        public int nivel { get; set; }
        public bool? activo { get; set; }
        public string descripcion { get; set; }
        public string solicitante { get; set; }
        public string analiza_recomienda { get; set; }
        public string autoriza_registra { get; set; }
        public string registra { get; set; }
    }
}