// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class adsiat_producto_servicio
    {
        public int codigo { get; set; }
        public string cuis { get; set; }
        public int? codigoactividad { get; set; }
        public int codigoproducto { get; set; }
        public string descripcionproducto { get; set; }
        public string nandina { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
    }
}