// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class adsiat_inicio_facturacion
    {
        public int codalmacen { get; set; }
        public DateTime? fecha_inicio { get; set; }
    }
}