// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class adsiat_recepcion_paquete_log
    {
        public int codigo { get; set; }
        public string cuis { get; set; }
        public int codclasificador { get; set; }
        public int codevento { get; set; }
        public int codrecepevento { get; set; }
        public string descripcion { get; set; }
        public DateTime? fechainicio { get; set; }
        public DateTime? fechafin { get; set; }
        public string horainicio { get; set; }
        public string horafin { get; set; }
        public string cufd { get; set; }
        public string cufd_evento { get; set; }
        public int? codestado_paquete { get; set; }
        public string codrecep_paquete { get; set; }
        public DateTime fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
        public bool? paquete_valido { get; set; }
    }
}