// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class audit_vtas_vendedor
    {
        public int codigo { get; set; }
        public int codalmacen { get; set; }
        public string codcliente { get; set; }
        public string razonsocial { get; set; }
        public string id { get; set; }
        public int numeroid { get; set; }
        public DateTime fecha { get; set; }
        public int codvendedor { get; set; }
        public int codvend_clie { get; set; }
        public int? codvend_traslado { get; set; }
        public int codvend_nr { get; set; }
        public int codvend_cbza { get; set; }
    }
}