// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class audit_202FP01
    {
        public string id { get; set; }
        public int numeroid { get; set; }
        public DateTime fecha { get; set; }
        public decimal total { get; set; }
        public string codmoneda { get; set; }
        public decimal tdc { get; set; }
        public int codigo { get; set; }
        public int coddocumento { get; set; }
        public byte codtipodoc { get; set; }
        public string cliente { get; set; }
        public short nrocuota { get; set; }
        public decimal monto { get; set; }
        public decimal? montopagado { get; set; }
        public DateTime vencimiento { get; set; }
        public string moneda { get; set; }
        public decimal? ttlpagos { get; set; }
        public decimal? ttlaux1 { get; set; }
        public decimal? ttlaux2 { get; set; }
        public decimal? ttlaux3 { get; set; }
        public decimal? ttlaux4 { get; set; }
    }
}