// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class audit_traslados
    {
        public string codcliente { get; set; }
        public string razonsocial { get; set; }
        public int? codvendedor_clie { get; set; }
        public int? codvendedor_nr { get; set; }
        public int? codvendedor_rep { get; set; }
        public int? codvendedor_Traslado { get; set; }
    }
}