// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class cncomprobante_backup
    {
        public int codigo { get; set; }
        public int? numero { get; set; }
        public string id { get; set; }
        public int numeroid { get; set; }
        public DateTime fecha { get; set; }
        public int codalmacen { get; set; }
        public string glosa { get; set; }
        public bool aprobado { get; set; }
        public string moneda { get; set; }
        public decimal factor { get; set; }
        public string monedabase { get; set; }
        public bool mayorizado { get; set; }
        public bool ajuste { get; set; }
        public string codtipo { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
    }
}