// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class cncuenta_distribucion
    {
        public string codcuenta { get; set; }
        public int? centrocosto_origen { get; set; }
        public int? centrocosto_destino { get; set; }
        public decimal? porcentaje { get; set; }
        public int? mes { get; set; }
    }
}