// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class cnmoldebg1
    {
        public string codmoldebg { get; set; }
        public int? nro { get; set; }
        public string signo { get; set; }
        public string codcuenta { get; set; }
        public string glosa { get; set; }
        public bool? esvalor { get; set; }
        public bool? niv1 { get; set; }
        public bool? niv2 { get; set; }
        public bool? niv3 { get; set; }
        public bool? niv4 { get; set; }
        public bool? estotal { get; set; }
    }
}