// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class cnpresupuesto
    {
        public int codperiodo { get; set; }
        public string codcuenta { get; set; }
        public int presupuestado { get; set; }
        public int ejecutado { get; set; }
    }
}