// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class cnresumenie_30
    {
        public string codcuenta { get; set; }
        public string nombrecuenta { get; set; }
        public string auxiliar { get; set; }
        public bool? imputable { get; set; }
        public int? tipo { get; set; }
        public decimal? ENERO_2020 { get; set; }
        public decimal? FEBRERO_2020 { get; set; }
        public decimal? MARZO_2020 { get; set; }
        public decimal? ABRIL_2020 { get; set; }
        public decimal? MAYO_2020 { get; set; }
        public decimal? JUNIO_2020 { get; set; }
        public decimal? JULIO_2020 { get; set; }
        public decimal? AGOSTO_2020 { get; set; }
        public decimal? SEPTIEMBRE_2020 { get; set; }
        public decimal? OCTUBRE_2020 { get; set; }
        public decimal? NOVIEMBRE_2020 { get; set; }
        public decimal? DICIEMBRE_2020 { get; set; }
    }
}