// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class cocuentab_conta_ag
    {
        public string codcuentab { get; set; }
        public string codunidad { get; set; }
        public int? codalmacen { get; set; }
        public string cta { get; set; }
        public string cta_aux { get; set; }
        public int? cta_cc { get; set; }
        public string cta_itf { get; set; }
        public string cta_itf_aux { get; set; }
        public int? cta_itf_cc { get; set; }
        public string cta_itf2 { get; set; }
        public string cta_itf2_aux { get; set; }
        public int? cta_itf2_cc { get; set; }
        public string cta_pendiente { get; set; }
        public string cta_pendiente_aux { get; set; }
        public int? cta_pendiente_cc { get; set; }
        public string cta_vta_contado { get; set; }
        public string cta_vta_contado_aux { get; set; }
        public int? cta_vta_contado_cc { get; set; }
    }
}