// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class comora
    {
        public int codcobranza { get; set; }
        public DateTime fecha { get; set; }
        public decimal monto { get; set; }
        public int moneda { get; set; }
        public int comprobante { get; set; }
        public byte estado { get; set; }
        public int nrorecibo { get; set; }
        public string codtalonario { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
    }
}