// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class comporta
    {
        public string COD { get; set; }
        public DateTime? FECHA { get; set; }
        public string COMPORTA1 { get; set; }
    }
}