// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class cpcobranza
    {
        public int codigo { get; set; }
        public string id { get; set; }
        public int numeroid { get; set; }
        public string descripcion { get; set; }
        public DateTime fecha { get; set; }
        public int codcomprador { get; set; }
        public int? codproveedor { get; set; }
        public decimal? monto { get; set; }
        public string moneda { get; set; }
        public decimal? montorest { get; set; }
        public byte estado { get; set; }
        public bool autorizada { get; set; }
        public int? tipopago { get; set; }
        public string codcuentab { get; set; }
        public int? comprobante { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
        public int? contabilizada { get; set; }
        public int? codalmacen { get; set; }
        public bool? anulada { get; set; }
        public string idchequera { get; set; }
        public int? nrocheque { get; set; }
        public string idcuenta { get; set; }
        public int? if_tipo_transaccion { get; set; }
        public string if_nro_documento { get; set; }
        public int? if_tipo_documento { get; set; }
        public DateTime? if_fecha_documento { get; set; }
        public string if_codbanco { get; set; }
        public string if_nro_cuenta { get; set; }
        public string id_compra { get; set; }
        public int? numeroid_compra { get; set; }
    }
}