// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class cpembarque
    {
        public int codigo { get; set; }
        public string id { get; set; }
        public int numeroid { get; set; }
        public int codproveedor { get; set; }
        public int codcomprador { get; set; }
        public int codalmacen { get; set; }
        public DateTime fecha { get; set; }
        public string codmoneda { get; set; }
        public decimal tdc { get; set; }
        public DateTime fechaemb { get; set; }
        public DateTime fechaest { get; set; }
        public string nomtrans { get; set; }
        public string tipotrans { get; set; }
        public bool contabilizado { get; set; }
        public decimal totalmonto { get; set; }
        public decimal totalpeso { get; set; }
        public decimal totalcosto { get; set; }
        public decimal total { get; set; }
        public bool anulada { get; set; }
        public string obs { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
        public string documento { get; set; }
        public string fecha_documento { get; set; }
    }
}