// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class cpodc1
    {
        public int? codigo { get; set; }
        public int cododc { get; set; }
        public string coditem { get; set; }
        public string codproveedor { get; set; }
        public decimal peso { get; set; }
        public decimal precio { get; set; }
        public decimal cantidad { get; set; }
        public decimal totalpeso { get; set; }
        public decimal totalprecio { get; set; }
        public decimal? cantllegada { get; set; }
        public decimal? cantembarcada { get; set; }
    }
}