// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class cpplancompra
    {
        public int codigo { get; set; }
        public string descripcion { get; set; }
        public int nrocuotas { get; set; }
        public short diascuota { get; set; }
        public decimal porceninicial { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
    }
}