// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class cpplancompra1
    {
        public int codigo { get; set; }
        public int nrocuota { get; set; }
        public int dias { get; set; }
        public decimal porcen { get; set; }
    }
}