// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class cpproveedor
    {
        public int codigo { get; set; }
        public string razonsocial { get; set; }
        public string contacto { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string obs { get; set; }
        public int codplancompra { get; set; }
        public int? codcomprador { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
        public string condicion { get; set; }
        public string direccion { get; set; }
        public string codlocalidad { get; set; }
        public string codtipo_identidad { get; set; }
        public string nit { get; set; }
    }
}