// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class crconsol_solofc
    {
        public string idfc { get; set; }
        public int? nroidfc { get; set; }
    }
}