// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class crmllamada
    {
        public int codigo { get; set; }
        public string id { get; set; }
        public int? codcaso { get; set; }
        public string codcuenta { get; set; }
        public int? idasunto { get; set; }
        public string asunto { get; set; }
        public string contenido { get; set; }
        public DateTime? fecha { get; set; }
        public int? horai { get; set; }
        public int? minutoi { get; set; }
        public int? nrotelefono { get; set; }
        public string usuario { get; set; }
        public string tipo { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
        public int? horaf { get; set; }
        public int? minutof { get; set; }
        public string otravez { get; set; }
        public int? minutos { get; set; }
        public string contacto { get; set; }
        public int? id_transporte { get; set; }
        public string guia { get; set; }
    }
}