// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class crmtarea
    {
        public int codigo { get; set; }
        public int? codcaso { get; set; }
        public string codcuenta { get; set; }
        public DateTime? fecha { get; set; }
        public DateTime? f_programada { get; set; }
        public int? hora_programada { get; set; }
        public int? minuto_programada { get; set; }
        public string usuario { get; set; }
        public string asunto { get; set; }
        public string contenido { get; set; }
        public string estado { get; set; }
    }
}