// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class csconversiones
    {
        public int codigo { get; set; }
        public string coditem_origen { get; set; }
        public decimal cuantos { get; set; }
        public string coditem_destino { get; set; }
    }
}