// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class csgastoembarque
    {
        public int codembarque { get; set; }
        public int codgasto { get; set; }
        public decimal monto { get; set; }
        public string codmoneda { get; set; }
        public decimal montodoc { get; set; }
        public string metodo { get; set; }
    }
}