// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class ctrl_pedidosnotatend
    {
        public int? codalmacen { get; set; }
        public string codcliente { get; set; }
        public int? codproforma { get; set; }
        public string id { get; set; }
        public int? numeroid { get; set; }
        public DateTime? fecha { get; set; }
        public string coditem { get; set; }
        public decimal? pendiente { get; set; }
        public decimal? ingreso { get; set; }
        public decimal? saldo { get; set; }
        public decimal? entrega { get; set; }
    }
}