// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class dm_venta_mensual_facturas
    {
        public int? codvendedor { get; set; }
        public string codcliente { get; set; }
        public int? mes { get; set; }
        public int? anio { get; set; }
        public decimal? total_mn { get; set; }
        public decimal? total_me { get; set; }
        public decimal? total_kg { get; set; }
    }
}