// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class es_parametros
    {
        public string servidor_opcional { get; set; }
        public string bd_opcional { get; set; }
        public string work_folder { get; set; }
        public bool? usar_linked_server { get; set; }
        public string enlace_210_68 { get; set; }
        public string enlace_68_210 { get; set; }
        public string bdd_enlace { get; set; }
    }
}