// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class es_ventascondesc
    {
        public int? codalmacen { get; set; }
        public string idrem { get; set; }
        public int? nroidrem { get; set; }
        public string idfac { get; set; }
        public int? nroidfac { get; set; }
        public int? codremision { get; set; }
        public string codcliente { get; set; }
        public int? anio { get; set; }
        public int? mes { get; set; }
        public decimal? ttl_pl { get; set; }
        public decimal? ttl_des_prov { get; set; }
        public decimal? ttl_des_vol { get; set; }
        public decimal? ttl_deslinea { get; set; }
        public decimal? ttl_sub { get; set; }
        public decimal? ttl_rec { get; set; }
        public decimal? ttl_desc { get; set; }
        public decimal? ttl_desc1 { get; set; }
        public decimal? ttl_desc2 { get; set; }
        public decimal? ttl_desc3 { get; set; }
        public decimal? ttl_desc4 { get; set; }
        public decimal? ttl_desc5 { get; set; }
        public decimal? ttl_otrosdesc { get; set; }
        public decimal? ttl_fac { get; set; }
    }
}