// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class es_vtas_nivel_desc_desc1
    {
        public int? anio { get; set; }
        public int? mes { get; set; }
        public int codalmacen { get; set; }
        public int codvendedor { get; set; }
        public string codcliente { get; set; }
        public string nomcliente { get; set; }
        public string codlinea { get; set; }
        public string desclinea { get; set; }
        public string niveldesc { get; set; }
        public int? coddescuento { get; set; }
        public string descdescto { get; set; }
        public decimal? ttl_us { get; set; }
        public decimal? ttl_kg { get; set; }
        public decimal? ttl_des { get; set; }
    }
}