// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class fncheque_cliente_remision
    {
        public string id_cheque { get; set; }
        public int? numeroid_cheque { get; set; }
        public string id_remision { get; set; }
        public int? numeroid_remision { get; set; }
        public decimal? monto { get; set; }
    }
}