// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class fndeposito_cliente
    {
        public int codigo { get; set; }
        public string id { get; set; }
        public int numeroid { get; set; }
        public int? codalmacen { get; set; }
        public DateTime? fecha { get; set; }
        public string codcliente { get; set; }
        public string codcuentab { get; set; }
        public decimal? monto { get; set; }
        public string codmoneda { get; set; }
        public decimal? factorme { get; set; }
        public string memo { get; set; }
        public bool anulada { get; set; }
        public bool contabilizada { get; set; }
        public int? comprobante { get; set; }
        public string horareg { get; set; }
        public DateTime? fechareg { get; set; }
        public string usuarioreg { get; set; }
        public decimal? itf { get; set; }
        public decimal? tdc { get; set; }
        public DateTime? fecha_conta { get; set; }
        public bool? verificado { get; set; }
        public bool? enlazar_cobranza { get; set; }
        public string idcobranza { get; set; }
        public int? numeroid_cobranza { get; set; }
        public decimal? monto_cobranza { get; set; }
        public string codmoneda_cobranza { get; set; }
        public decimal? monto_cambio { get; set; }
        public decimal? monto_me { get; set; }
        public bool? deposito_en_mora_habilita_descto { get; set; }
        public string nit { get; set; }
        public string nomcliente_nit { get; set; }
    }
}