// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class fndeudor_conta
    {
        public string iddeudor { get; set; }
        public string codunidad { get; set; }
        public int? codalmacen { get; set; }
        public string cta_porrendir_mn { get; set; }
        public string cta_porrendir_mn_aux { get; set; }
        public int? cta_porrendir_mn_cc { get; set; }
        public string cta_porrendir_me { get; set; }
        public string cta_porrendir_me_aux { get; set; }
        public int? cta_porrendir_me_cc { get; set; }
        public string cta_porcobrar_mn { get; set; }
        public string cta_porcobrar_mn_aux { get; set; }
        public int? cta_porcobrar_mn_cc { get; set; }
        public string cta_porcobrar_me { get; set; }
        public string cta_porcobrar_me_aux { get; set; }
        public int? cta_porcobrar_me_cc { get; set; }
        public string cta_porpagar_mn { get; set; }
        public string cta_porpagar_mn_aux { get; set; }
        public int? cta_porpagar_mn_cc { get; set; }
        public string cta_porpagar_me { get; set; }
        public string cta_porpagar_me_aux { get; set; }
        public int? cta_porpagar_me_cc { get; set; }
        public string cta_prestamo_mn { get; set; }
        public string cta_prestamo_mn_aux { get; set; }
        public int? cta_prestamo_mn_cc { get; set; }
        public string cta_anticipo_mn { get; set; }
        public string cta_anticipo_mn_aux { get; set; }
        public int? cta_anticipo_mn_cc { get; set; }
        public string cta_prestamo_me { get; set; }
        public string cta_prestamo_me_aux { get; set; }
        public int? cta_prestamo_me_cc { get; set; }
        public string cta_anticipo_me { get; set; }
        public string cta_anticipo_me_aux { get; set; }
        public int? cta_anticipo_me_cc { get; set; }
    }
}