// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class fndeudor_compuesto1
    {
        public string iddeudor_compuesto { get; set; }
        public string iddeudor { get; set; }
        public int? porcentaje { get; set; }
    }
}