// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class inconcepto_conta
    {
        public int? codconcepto { get; set; }
        public int? codalmacen { get; set; }
        public string codunidad { get; set; }
        public string cta_debe { get; set; }
        public string cta_debe_aux { get; set; }
        public int? cta_debe_cc { get; set; }
        public string cta_haber { get; set; }
        public string cta_haber_aux { get; set; }
        public int? cta_haber_cc { get; set; }
    }
}