// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class inconcepto
    {
        public int codigo { get; set; }
        public string descripcion { get; set; }
        public short factor { get; set; }
        public bool traspaso { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
        public bool? porcosto { get; set; }
        public int? codtarifa { get; set; }
        public int? codcontra_concepto { get; set; }
        public bool? usuario_final { get; set; }
        public bool? cliente { get; set; }
    }
}