// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class infisico1
    {
        public int codfisico { get; set; }
        public string coditem { get; set; }
        public decimal cantidad { get; set; }
        public string udm { get; set; }
        public decimal cantrevis { get; set; }
        public short fase { get; set; }
        public string codzona { get; set; }
    }
}