// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class infueradelinea
    {
        public string CODIGO { get; set; }
        public decimal? STOCK { get; set; }
        public decimal? PESO_1000_PZ { get; set; }
        public decimal? PRECIO_100_PZ { get; set; }
        public decimal? precio_unit { get; set; }
        public DateTime? desde { get; set; }
    }
}