// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class ininvconsol1
    {
        public int codinvconsol { get; set; }
        public string coditem { get; set; }
        public decimal cantreal { get; set; }
        public decimal cantsist { get; set; }
        public decimal dif { get; set; }
        public string udm { get; set; }
    }
}