// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class initem_valorcriterio
    {
        public string coditem { get; set; }
        public decimal? valor_criterio { get; set; }
        public DateTime? fecha { get; set; }
    }
}