// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class inlinea
    {
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public int? codgrupo { get; set; }
        public int? codgrupomer { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
        public string descdetallada { get; set; }
        public string codsubgrupo_vta { get; set; }
        public decimal? porcentaje_comis { get; set; }
    }
}