// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class inpedido
    {
        public int codigo { get; set; }
        public string id { get; set; }
        public int? numeroid { get; set; }
        public int codalmacen { get; set; }
        public int codalmdestino { get; set; }
        public DateTime fecha { get; set; }
        public string obs { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
    }
}