// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class intarifa_historico1
    {
        public int? codhistorico { get; set; }
        public int codtarifa { get; set; }
        public string item { get; set; }
        public decimal? precio { get; set; }
    }
}