// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class itemdesdet
    {
        public string CODLINEA { get; set; }
        public string CODITEM { get; set; }
        public string DESCRIP { get; set; }
        public string DET { get; set; }
        public string MEDIDA { get; set; }
    }
}