// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class mamaterial
    {
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public string desccort { get; set; }
        public string ud { get; set; }
        public int? codlinea { get; set; }
        public string tamanio { get; set; }
        public string marca { get; set; }
        public string color { get; set; }
        public string origen { get; set; }
        public string obs { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
    }
}