// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class pealtabaja
    {
        public int? codpersona { get; set; }
        public DateTime? fechaalta { get; set; }
        public DateTime? fechabaja { get; set; }
        public bool haybaja { get; set; }
        public string obs { get; set; }
    }
}