// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class pebonoant
    {
        public byte anodel { get; set; }
        public byte anoal { get; set; }
        public decimal monto { get; set; }
        public string moneda { get; set; }
        public byte porcentaje { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
    }
}