// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class pecargo_tramo
    {
        public int codigo { get; set; }
        public string descripcion { get; set; }
        public int? codgrupo_objetivo { get; set; }
        public int? codarea1 { get; set; }
        public decimal? porcen_tienda1 { get; set; }
        public decimal? porcen_externo1 { get; set; }
        public decimal? total_area1 { get; set; }
        public int? codarea2 { get; set; }
        public decimal? porcen_tienda2 { get; set; }
        public decimal? porcen_externo2 { get; set; }
        public decimal? total_area2 { get; set; }
        public int? codarea3 { get; set; }
        public decimal? porcen_tienda3 { get; set; }
        public decimal? porcen_externo3 { get; set; }
        public decimal? total_area3 { get; set; }
        public decimal? porcen_tienda4 { get; set; }
        public decimal? porcen_externo4 { get; set; }
        public decimal? total_area4 { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
    }
}