// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class pecontrato
    {
        public int codigo { get; set; }
        public string id { get; set; }
        public int numeroid { get; set; }
        public int codpersona { get; set; }
        public DateTime? fechaalta { get; set; }
        public DateTime? fechabaja { get; set; }
        public string haybaja { get; set; }
        public string obsalta { get; set; }
        public bool? estado { get; set; }
        public bool? anulado { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
        public string obsbaja { get; set; }
    }
}