// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class pecomviajante_detalle1
    {
        public int? codplanilla { get; set; }
        public int? codvendedor { get; set; }
        public int? cartera { get; set; }
        public int? codpersona { get; set; }
        public decimal? porcencomventas { get; set; }
        public decimal? porcencomcbzas { get; set; }
        public decimal? porcencom_solorecu { get; set; }
        public string codmoneda { get; set; }
        public decimal? totaldist { get; set; }
        public decimal? tot_monto_excluido { get; set; }
        public decimal? tot_cbza_nopagacomis { get; set; }
        public decimal? tot_rechazado { get; set; }
        public decimal? tot_item_sc { get; set; }
        public decimal? totaldist_paracomis { get; set; }
        public decimal? desc_iva { get; set; }
        public decimal? neto_paracomision { get; set; }
        public decimal? comision { get; set; }
        public decimal? comcbza { get; set; }
        public decimal? comvta { get; set; }
        public decimal? comtotal { get; set; }
    }
}