// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class pecomision
    {
        public int codigo { get; set; }
        public int mes { get; set; }
        public int ano { get; set; }
        public string codempresa { get; set; }
        public bool cerrado { get; set; }
        public DateTime tdcafecha { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
    }
}