// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class peexperiencia
    {
        public int codigo { get; set; }
        public int codper { get; set; }
        public string empresa { get; set; }
        public string ubicacion { get; set; }
        public string cargo { get; set; }
        public DateTime fechaini { get; set; }
        public DateTime fechafin { get; set; }
        public int sueldoinicial { get; set; }
        public int sueldofinal { get; set; }
        public string moneda { get; set; }
        public string motivoret { get; set; }
        public string obs { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
    }
}