// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class peliquidacion
    {
        public int codigo { get; set; }
        public int? ano { get; set; }
        public byte? mes { get; set; }
        public int? codtipoliquidacion { get; set; }
        public bool cerrado { get; set; }
        public string codbanco { get; set; }
        public string codempresa { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
        public DateTime? fechapago { get; set; }
        public DateTime? fechadeposito { get; set; }
        public string lugar { get; set; }
    }
}