// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class pepaguinaldo_descuentos
    {
        public string codplanilla { get; set; }
        public string codpersona { get; set; }
        public decimal? monto { get; set; }
        public string obs { get; set; }
    }
}