// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class peplansubsidio
    {
        public int codigo { get; set; }
        public int? codpersona { get; set; }
        public int? codvariable { get; set; }
        public bool efectivo { get; set; }
        public DateTime? desde { get; set; }
        public DateTime? hasta { get; set; }
        public int? nroactual { get; set; }
        public int? duracion { get; set; }
        public decimal? monto { get; set; }
        public string codmoneda { get; set; }
        public DateTime? fechanacmto { get; set; }
        public bool hayfechanacmto { get; set; }
        public string obs { get; set; }
        public bool anulado { get; set; }
        public string fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
        public DateTime? fechacertificado { get; set; }
        public bool? hayfechacerti { get; set; }
        public string tipo { get; set; }
    }
}