// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class peplancomision4
    {
        public int codigo { get; set; }
        public int coddetalle { get; set; }
        public string item { get; set; }
        public decimal porcentaje { get; set; }
    }
}