// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class pepsueldo1_aa
    {
        public int codplanilla { get; set; }
        public int codpersona { get; set; }
        public decimal? faltas { get; set; }
        public decimal? diaspagado { get; set; }
        public decimal? hrspagado { get; set; }
        public decimal? habermensual { get; set; }
        public decimal? haberdiario { get; set; }
        public decimal? haberbasico { get; set; }
        public int? anosantiguedad { get; set; }
        public decimal? bonoantiguedad { get; set; }
        public decimal? horasextras { get; set; }
        public decimal? bonohrsextras { get; set; }
        public decimal? comision { get; set; }
        public decimal? prima { get; set; }
        public decimal? otrosingc { get; set; }
        public decimal? TotalCotizable { get; set; }
        public decimal? subsidios { get; set; }
        public decimal? otrosingnc { get; set; }
        public decimal? TotalGanado { get; set; }
        public decimal? afp { get; set; }
        public decimal? rciva { get; set; }
        public decimal? acreedor { get; set; }
        public decimal? otrosdesc { get; set; }
        public decimal? TotalDesc { get; set; }
        public decimal? Liquido { get; set; }
    }
}