// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class pepsueldos_contabilizacion
    {
        public int? codplanilla { get; set; }
        public int? mes { get; set; }
        public int? anio { get; set; }
        public string tipo { get; set; }
        public string id { get; set; }
        public int? numeroid { get; set; }
        public DateTime? fecha { get; set; }
    }
}