// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class peptributaria_inicial
    {
        public int anio { get; set; }
        public int mes { get; set; }
        public int CodPersona { get; set; }
        public decimal saldo_inicial { get; set; }
    }
}