// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class perango_comision1
    {
        public int codrango { get; set; }
        public decimal desde_objetivo { get; set; }
        public decimal hasta_objetivo { get; set; }
        public decimal? porcen_comision { get; set; }
    }
}