// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class pevariable_conta
    {
        public int codvariable { get; set; }
        public int codalmacen { get; set; }
        public string cta { get; set; }
        public string cta_aux { get; set; }
        public int? cta_cc { get; set; }
        public string cta_iva { get; set; }
        public string cta_iva_aux { get; set; }
        public int? cta_iva_cc { get; set; }
        public string cta_por_pagar { get; set; }
        public string cta_por_pagar_aux { get; set; }
        public int? cta_por_pagar_cc { get; set; }
    }
}