// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class promocion_esp
    {
        public string codcliente { get; set; }
        public int? codvendedor { get; set; }
        public decimal? venta_obj { get; set; }
        public decimal? venta_real { get; set; }
        public decimal? dif { get; set; }
        public decimal? g1 { get; set; }
        public decimal? g2 { get; set; }
        public decimal? g3 { get; set; }
        public decimal? g4 { get; set; }
        public decimal? g5 { get; set; }
        public decimal? g6 { get; set; }
        public decimal? g7 { get; set; }
        public decimal? g8 { get; set; }
        public decimal? promocion { get; set; }
    }
}