// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class pv720899
    {
        public int? orden { get; set; }
        public string codcliente { get; set; }
        public string nomcliente { get; set; }
        public string lugar { get; set; }
        public string depto { get; set; }
        public string provincia { get; set; }
        public string clasificacion { get; set; }
        public decimal? total { get; set; }
        public decimal? promedio { get; set; }
        public decimal? porcentaje { get; set; }
        public decimal? acumulado { get; set; }
        public short? hito { get; set; }
        public decimal? col_1 { get; set; }
        public decimal? col_2 { get; set; }
    }
}