// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class repclientes
    {
        public int? codalmacen { get; set; }
        public string codcliente { get; set; }
        public string razonsocial { get; set; }
        public string nit { get; set; }
        public int? codvendedor { get; set; }
        public string rubro { get; set; }
        public decimal? promedio { get; set; }
        public int? nropedidos_urg { get; set; }
        public int? nropedidos_nor { get; set; }
        public int? codptoventa { get; set; }
        public string desc_ptoventa { get; set; }
        public string direccion { get; set; }
        public decimal? nro_meses { get; set; }
        public decimal? vta_enero { get; set; }
        public decimal? vta_febrero { get; set; }
        public decimal? vta_marzo { get; set; }
        public decimal? vta_abril { get; set; }
        public decimal? vta_mayo { get; set; }
        public decimal? vta_junio { get; set; }
        public decimal? vta_julio { get; set; }
        public decimal? vta_agosto { get; set; }
        public decimal? vta_septiembre { get; set; }
        public decimal? vta_octubre { get; set; }
        public decimal? vta_noviembre { get; set; }
        public decimal? vta_diciembre { get; set; }
        public string precio_1 { get; set; }
        public string precio_2 { get; set; }
        public string precio_3 { get; set; }
        public int? nro_tiendas { get; set; }
    }
}