// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class repesaldosfc1_back
    {
        public int codreporte { get; set; }
        public string codalmacen { get; set; }
        public string codvendedor { get; set; }
        public string codcliente { get; set; }
        public string nomcliente { get; set; }
        public decimal? saldo_anterior { get; set; }
        public decimal? cargos { get; set; }
        public decimal? dev_anticipo { get; set; }
        public decimal? creditos { get; set; }
        public decimal? abonos { get; set; }
        public decimal? revanticipo { get; set; }
        public decimal? saldo_periodo { get; set; }
        public decimal? saldo_final { get; set; }
        public string tipo_saldo { get; set; }
        public int? anio { get; set; }
        public int? mes { get; set; }
    }
}