// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class reporte_jra
    {
        public string codigo { get; set; }
        public string razonsocial { get; set; }
        public string nit { get; set; }
        public int? codvendedor { get; set; }
        public string ptoventa { get; set; }
        public string descripcion { get; set; }
    }
}