// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class revisa_fac_marzo13
    {
        public int? codremision { get; set; }
        public decimal? ttl_kg_nr { get; set; }
        public decimal? ttl_kg_fc { get; set; }
        public decimal? dif { get; set; }
    }
}