// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class saldotemp_resumido
    {
        public int? codalmacen { get; set; }
        public string codlinea { get; set; }
        public string coditem { get; set; }
        public decimal? si { get; set; }
        public decimal? si_linea { get; set; }
        public decimal? porcen_item_si { get; set; }
        public decimal? costoi { get; set; }
        public decimal? costoi_ponderado { get; set; }
        public decimal? toti { get; set; }
        public decimal? toti_ponderado { get; set; }
        public decimal? sf { get; set; }
        public decimal? sf_linea { get; set; }
        public decimal? porcen_item_sf { get; set; }
        public decimal? costof { get; set; }
        public decimal? costof_ponderado { get; set; }
        public decimal? totf { get; set; }
        public decimal? totf_ponderado { get; set; }
        public decimal? cantnm_transito { get; set; }
        public decimal? cantnm_transito_linea { get; set; }
        public decimal? porcen_item_transito { get; set; }
        public decimal? costo_transito_ponderado { get; set; }
        public decimal? total_transito { get; set; }
        public decimal? total_transito_ponderado { get; set; }
    }
}