// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class saldotemp_ags_resultado_resumido
    {
        public string codlinea { get; set; }
        public string coditem { get; set; }
        public decimal? si { get; set; }
        public decimal? si_linea { get; set; }
        public decimal? porcen_item_si { get; set; }
        public decimal? costoi { get; set; }
        public decimal? costoi_ponderado { get; set; }
        public decimal? toti { get; set; }
        public decimal? toti_ponderado { get; set; }
        public decimal? oi { get; set; }
        public decimal? oi_linea { get; set; }
        public decimal? porcen_item_oi { get; set; }
        public decimal? costo_oi { get; set; }
        public decimal? costo_oi_ponderado { get; set; }
        public decimal? tot_oi { get; set; }
        public decimal? tot_oi_ponderado { get; set; }
        public decimal? cp { get; set; }
        public decimal? cp_linea { get; set; }
        public decimal? porcen_item_cp { get; set; }
        public decimal? costo_cp { get; set; }
        public decimal? costo_cp_ponderado { get; set; }
        public decimal? tot_cp { get; set; }
        public decimal? tot_cp_ponderado { get; set; }
        public decimal? vt { get; set; }
        public decimal? vt_linea { get; set; }
        public decimal? porcen_item_vt { get; set; }
        public decimal? costo_vt { get; set; }
        public decimal? costo_vt_ponderado { get; set; }
        public decimal? tot_vt { get; set; }
        public decimal? tot_vt_ponderado { get; set; }
        public decimal? ns { get; set; }
        public decimal? ns_linea { get; set; }
        public decimal? porcen_item_ns { get; set; }
        public decimal? costo_ns { get; set; }
        public decimal? costo_ns_ponderado { get; set; }
        public decimal? tot_ns { get; set; }
        public decimal? tot_ns_ponderado { get; set; }
        public decimal? sf { get; set; }
        public decimal? sf_linea { get; set; }
        public decimal? porcen_item_sf { get; set; }
        public decimal? costo_sf { get; set; }
        public decimal? costo_sf_ponderado { get; set; }
        public decimal? tot_sf { get; set; }
        public decimal? tot_sf_ponderado { get; set; }
        public decimal? transito { get; set; }
        public decimal? transito_linea { get; set; }
        public decimal? porcen_item_transito { get; set; }
        public decimal? costo_transito { get; set; }
        public decimal? costo_transito_ponderado { get; set; }
        public decimal? tot_transito { get; set; }
        public decimal? tot_transito_ponderado { get; set; }
    }
}