// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class selog
    {
        public long id { get; set; }
        public string usuario { get; set; }
        public DateTime? fecha { get; set; }
        public string hora { get; set; }
        public string entidad { get; set; }
        public string codigo { get; set; }
        public string id_doc { get; set; }
        public string numeroid_doc { get; set; }
        public string ventana { get; set; }
        public string detalle { get; set; }
        public string tipo { get; set; }
    }
}