// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class seprograma1
    {
        public int codigo { get; set; }
        public byte orden { get; set; }
        public string descripcion { get; set; }
    }
}