// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace siaw_DBContext.Models
{
    public partial class SIA00002_TipoCambioResult
    {
        [Column("TDC", TypeName = "decimal(18,8)")]
        public decimal? TDC { get; set; }
    }
}
