// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class slDHL
    {
        public int codigo { get; set; }
        public string P1NROCUENTA { get; set; }
        public string P1SEGUROENVIO { get; set; }
        public string P2NROCUENTA { get; set; }
        public string P2REMITENTE { get; set; }
        public string P2REF { get; set; }
        public string P2NOMBEMPRESA { get; set; }
        public string P2DIRECC { get; set; }
        public string P2CODPOSTAL { get; set; }
        public string P2TELF { get; set; }
        public string P3NOMBRE { get; set; }
        public string P3DIRECC { get; set; }
        public string P3CODPOSTAL { get; set; }
        public string P3PAIS { get; set; }
        public string P3CONTACTO { get; set; }
        public string P3TELF { get; set; }
        public int? P4NROPZ { get; set; }
        public decimal? P4PESO { get; set; }
        public string P5DESC { get; set; }
        public string P6VALOR { get; set; }
        public string P6CODADUANA { get; set; }
        public DateTime? FECHA { get; set; }
        public string ORIGEN { get; set; }
        public string CODDESTINO { get; set; }
        public decimal? P8PESO { get; set; }
        public decimal? P8OTROS { get; set; }
        public decimal? P8SEGURO { get; set; }
        public decimal? P8VAT { get; set; }
        public string P8MON { get; set; }
        public decimal? P8TOTAL { get; set; }
        public string P8NROETIQUETA { get; set; }
        public string P8NROPAGO { get; set; }
        public string P8TIPO { get; set; }
        public string P8VENCE { get; set; }
        public string P8RECOGIDOPOR { get; set; }
        public string P8RUTA { get; set; }
        public string P8HORA { get; set; }
        public DateTime? P8FECHA { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
    }
}