// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class solurg_403840
    {
        public string id { get; set; }
        public int? numeroid { get; set; }
        public int? codalmdestino { get; set; }
        public DateTime? fecha { get; set; }
        public int? codvendedor { get; set; }
        public string codcliente { get; set; }
        public string idnm { get; set; }
        public int? numeroidnm { get; set; }
        public string idfc { get; set; }
        public int? numeroidfc { get; set; }
        public string coditem { get; set; }
        public decimal? cantidad { get; set; }
        public string coditemn { get; set; }
        public int? codtarifa { get; set; }
        public string razonsocial { get; set; }
        public DateTime? fechaf { get; set; }
        public int? dias { get; set; }
        public decimal? cantidadf { get; set; }
        public decimal? diferencia { get; set; }
        public decimal? icantidad { get; set; }
        public decimal? icantidadk { get; set; }
        public decimal? icantidad2 { get; set; }
        public decimal? icantidadk2 { get; set; }
        public int? diasnh { get; set; }
        public int? coddocumento { get; set; }
        public int? coddocumentor { get; set; }
        public decimal? multa { get; set; }
    }
}