// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class tblcontrol
    {
        public byte? tipo { get; set; }
        public DateTime? fecha { get; set; }
        public int? codpersona { get; set; }
        public bool infraccion { get; set; }
        public bool valido { get; set; }
        public string razon { get; set; }
        public string obs { get; set; }
        public int? hlim { get; set; }
        public int? mlim { get; set; }
        public int? h { get; set; }
        public int? m { get; set; }
        public string seguridad { get; set; }
        public int codigo { get; set; }
    }
}