// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class tblpersona
    {
        public int numero { get; set; }
        public string codigo_tickeo { get; set; }
        public string ci { get; set; }
        public string ci_expedido { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public DateTime? f_nacimiento { get; set; }
        public string edo_civil { get; set; }
        public DateTime? f_ingreso { get; set; }
        public DateTime? f_termino { get; set; }
        public bool activa { get; set; }
        public int? codagencia { get; set; }
        public int? turno { get; set; }
        public double? hrs_x_semana { get; set; }
        public bool horario_libre { get; set; }
        public bool recive_vacacion { get; set; }
        public double? saldo_inicial { get; set; }
        public DateTime? f_saldo { get; set; }
        public string obs { get; set; }
        public byte[] template { get; set; }
        public byte[] template2 { get; set; }
        public bool permite_teclado { get; set; }
        public int codigo { get; set; }
    }
}