// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class temp_auditpagosnr
    {
        public string tipo { get; set; }
        public string cliente { get; set; }
        public int? codproforma { get; set; }
        public int? codremision { get; set; }
        public bool? tipopago { get; set; }
        public bool? contra_entrega { get; set; }
        public bool? pagado_con_anticipo { get; set; }
        public string ID { get; set; }
        public int? NUMEROID { get; set; }
        public DateTime? fecha { get; set; }
        public decimal? total { get; set; }
        public decimal? tdc { get; set; }
        public string codmoneda { get; set; }
        public int? codcuota { get; set; }
        public int? nrocuota { get; set; }
        public decimal? monto { get; set; }
        public decimal? montopagado { get; set; }
        public DateTime? vencimiento { get; set; }
        public decimal? PAGADO { get; set; }
        public decimal? DIF { get; set; }
        public decimal? DIF1 { get; set; }
        public decimal? pago_cbza { get; set; }
        public decimal? pago_cbza_contado { get; set; }
    }
}