// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class temp_auditpagosnr_contado
    {
        public string tipo { get; set; }
        public string cliente { get; set; }
        public int? codproforma { get; set; }
        public string idPF { get; set; }
        public int? nroidPF { get; set; }
        public bool? tipopagoNR { get; set; }
        public bool? tipopagoPF { get; set; }
        public bool? contra_entrega { get; set; }
        public bool? pago_contado_anticipado { get; set; }
        public int? codremision { get; set; }
        public string idnr { get; set; }
        public int? nroidnr { get; set; }
        public DateTime? fecha { get; set; }
        public string nomcliente { get; set; }
        public string nit { get; set; }
        public int? nro_factura { get; set; }
        public DateTime? vencimiento { get; set; }
        public decimal? ttlventa { get; set; }
        public decimal? tdc { get; set; }
        public string codmoneda { get; set; }
        public int? codcuota { get; set; }
        public int? nrocuota { get; set; }
        public decimal? ttl_cbza_CB { get; set; }
        public decimal? ttl_cbza_CZ { get; set; }
        public decimal? rev_anticipo_a_una_prof { get; set; }
        public decimal? rev_anticipo_a_varias_prof { get; set; }
        public decimal? ttl_pagado { get; set; }
        public decimal? saldo { get; set; }
        public decimal? dif { get; set; }
    }
}