// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class temp_DTDM_rev_anticipos_314
    {
        public int? codcobranza { get; set; }
        public DateTime? fecha { get; set; }
    }
}