// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class temp_listaclie_esaldosfc_226_942_649_866_674_561_575_646_759_978_297_293_291_990_902_155_669
    {
        public string cambio { get; set; }
        public int? tipo { get; set; }
        public int antes { get; set; }
        public string codcliente { get; set; }
        public string razonsocial { get; set; }
        public int codalmacen { get; set; }
        public string tipo_saldo { get; set; }
    }
}