// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class temp_comisvedexterno87126
    {
        public int origen { get; set; }
        public bool? item_excluido { get; set; }
        public int codcobranza { get; set; }
        public int codptovta { get; set; }
        public string codcliente { get; set; }
        public int codremision { get; set; }
        public string id { get; set; }
        public int numeroid { get; set; }
        public string codmoneda { get; set; }
        public int? codvendedor { get; set; }
        public string NombVendedor { get; set; }
        public int codcomisiones { get; set; }
        public decimal cantidad { get; set; }
        public string coditem { get; set; }
        public decimal? totalitem_fact { get; set; }
        public decimal? totalitem_neto { get; set; }
        public decimal ttlpagado_kg { get; set; }
        public string codlinea { get; set; }
        public int? codgrupomer { get; set; }
        public string niveldesc { get; set; }
        public int codtarifa { get; set; }
        public int coddescuento { get; set; }
        public decimal? peso { get; set; }
        public DateTime fecha_venta { get; set; }
        public DateTime fecha_cbza { get; set; }
        public int? dias { get; set; }
        public decimal subtotal { get; set; }
        public decimal total { get; set; }
        public decimal? montopagado { get; set; }
        public string monpagado { get; set; }
        public int DeDias { get; set; }
        public int ADias { get; set; }
        public decimal porcen_dist { get; set; }
        public decimal monto_dist { get; set; }
        public decimal monto_dist_aux { get; set; }
        public decimal IVA_monto_dist { get; set; }
        public decimal por_comision { get; set; }
        public decimal por_comision_inc { get; set; }
        public decimal comision { get; set; }
        public decimal desctocomision { get; set; }
        public bool? anticipo_para_vta_contado { get; set; }
        public bool? contado_efectivo { get; set; }
        public bool? contra_entrega { get; set; }
        public bool? es_ajena { get; set; }
        public bool? pago_contado_anticipado { get; set; }
        public bool? es_nota_credito { get; set; }
    }
}