// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class temp_listaclie_esaldosfc_430_331_122_485_627_457_498_517_22_265
    {
        public string cambio { get; set; }
        public int? tipo { get; set; }
        public int antes { get; set; }
        public string codcliente { get; set; }
        public string razonsocial { get; set; }
        public int codalmacen { get; set; }
        public string tipo_saldo { get; set; }
    }
}