// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class temp_borrar
    {
        public string codfc { get; set; }
        public int? codalmacen { get; set; }
    }
}