// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class temp_costoventas741945337314_1
    {
        public int? codalmacen { get; set; }
        public string codlinea { get; set; }
        public string coditem { get; set; }
        public bool kit { get; set; }
        public decimal? ttl_ud { get; set; }
        public decimal? ttl_kg { get; set; }
        public decimal? ttl_sin_desc { get; set; }
        public decimal? precio_vta { get; set; }
        public decimal? ttl_con_desc { get; set; }
        public decimal? ttl_iva { get; set; }
        public decimal? ttl_vta_neta { get; set; }
        public decimal? costo_unit { get; set; }
        public decimal? ttl_costo { get; set; }
        public decimal? utilidad_bruta { get; set; }
        public decimal? porcentaje { get; set; }
    }
}