// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class unidos
    {
        public string codigo { get; set; }
        public int? punto { get; set; }
        public string descptoventa { get; set; }
    }
}