// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class vecliente2
    {
        public string codigo { get; set; }
        public string moneda { get; set; }
        public string razonsocial { get; set; }
        public string casilla { get; set; }
        public string nit { get; set; }
        public decimal? credito { get; set; }
        public DateTime? fvenccred { get; set; }
        public decimal? creditodisp { get; set; }
        public int codvendedor { get; set; }
        public DateTime? fapertura { get; set; }
        public string obs { get; set; }
        public string email { get; set; }
        public string garantia { get; set; }
        public int? codplanpago { get; set; }
        public string codrubro { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
        public bool? habilitado { get; set; }
        public byte? tipoventa { get; set; }
        public string condicion { get; set; }
        public int? max_nits { get; set; }
        public bool? controla_maximo { get; set; }
        public string situacion { get; set; }
        public string codtipo_identidad { get; set; }
        public bool? discrimina_iva { get; set; }
        public string codlocalidad { get; set; }
        public string nroingresosbrutos { get; set; }
        public string tipofactura { get; set; }
        public string tiponotacredito { get; set; }
        public decimal? iva { get; set; }
        public string clasificacion { get; set; }
        public int? coddsctos_credito { get; set; }
        public string cartera { get; set; }
        public bool? solo_pp { get; set; }
        public bool? contra_entrega { get; set; }
        public string tipo { get; set; }
        public bool? controla_empaque_cerrado { get; set; }
        public bool? controla_precios { get; set; }
        public decimal? visitas_x_mes { get; set; }
        public decimal? maximo_vta { get; set; }
        public string codmoneda_maximo_vta { get; set; }
        public int? codvendedor_asignado { get; set; }
        public bool? permite_items_repetidos { get; set; }
        public int? dias_reversion_items_especiales { get; set; }
        public string codzona { get; set; }
        public bool? es_cliente_final { get; set; }
        public bool? controla_empaque_minimo { get; set; }
        public bool? controla_monto_minimo { get; set; }
        public string nombre_contrato { get; set; }
        public string ci_contrato { get; set; }
    }
}