// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class veclientesiguales_credito
    {
        public string codcliente_a { get; set; }
        public decimal credito { get; set; }
        public decimal creditodisp { get; set; }
        public DateTime? fechareg { get; set; }
        public string usuarioreg { get; set; }
        public string horareg { get; set; }
        public string codtipocredito { get; set; }
        public string codmoneda { get; set; }
    }
}