// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class vedesitem_ptoventa
    {
        public int codptoventa { get; set; }
        public string nivel { get; set; }
    }
}