// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class vedesextra_excluyentes
    {
        public int coddesextra1 { get; set; }
        public int coddesextra2 { get; set; }
    }
}