// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class vedsctos_credito
    {
        public int codigo { get; set; }
        public string descripcion { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
        public decimal? extra_contado_porcen { get; set; }
        public decimal? extra_contado_minimo { get; set; }
        public string extra_contado_codmoneda { get; set; }
    }
}