// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class veetiquetas
    {
        public int codigo { get; set; }
        public string codcliente { get; set; }
        public string linea1 { get; set; }
        public string linea2 { get; set; }
        public string representante { get; set; }
        public string telefono { get; set; }
        public string ciudad { get; set; }
    }
}