// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class vefactura
    {
        public int codigo { get; set; }
        public string id { get; set; }
        public int numeroid { get; set; }
        public int? codremision { get; set; }
        public int codalmacen { get; set; }
        public string codcliente { get; set; }
        public string nomcliente { get; set; }
        public string nit { get; set; }
        public int codvendedor { get; set; }
        public string codmoneda { get; set; }
        public DateTime fecha { get; set; }
        public decimal tdc { get; set; }
        public byte tipopago { get; set; }
        public decimal subtotal { get; set; }
        public decimal descuentos { get; set; }
        public decimal recargos { get; set; }
        public decimal total { get; set; }
        public bool anulada { get; set; }
        public string transporte { get; set; }
        public string fletepor { get; set; }
        public string direccion { get; set; }
        public bool transferida { get; set; }
        public bool descarga { get; set; }
        public bool contabilizado { get; set; }
        public string nroorden { get; set; }
        public string alfanumerico { get; set; }
        public int nrofactura { get; set; }
        public short nrocaja { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
        public decimal? factorme { get; set; }
        public string nroautorizacion { get; set; }
        public DateTime? fechalimite { get; set; }
        public string codigocontrol { get; set; }
        public decimal? iva { get; set; }
        public string idfc { get; set; }
        public int? numeroidfc { get; set; }
        public int? codtipopago { get; set; }
        public string codcuentab { get; set; }
        public string codbanco { get; set; }
        public string nrocheque { get; set; }
        public string idcuenta { get; set; }
        public string tipo { get; set; }
        public string nrolugar { get; set; }
        public string condicion { get; set; }
        public string codtipo_comprobante { get; set; }
        public int? comprobante { get; set; }
        public string odc { get; set; }
        public decimal? peso { get; set; }
        public bool? notadebito { get; set; }
        public string version_tarifa { get; set; }
        public DateTime? fecha_anulacion { get; set; }
        public string idanticipo { get; set; }
        public int? numeroidanticipo { get; set; }
        public string cae { get; set; }
        public string fecha_cae { get; set; }
        public decimal? monto_anticipo { get; set; }
        public string motivo_anulacion { get; set; }
        public bool? contra_entrega { get; set; }
        public string nroticket { get; set; }
        public string codcliente_real { get; set; }
        public string estado_contra_entrega { get; set; }
        public bool? refacturar { get; set; }
        public int? codproforma { get; set; }
        public string complemento_ci { get; set; }
        public int? tipo_venta { get; set; }
        public string cufd { get; set; }
        public string cuf { get; set; }
        public bool? en_linea { get; set; }
        public bool? en_linea_SIN { get; set; }
        public int? tipo_docid { get; set; }
        public string email { get; set; }
        public string leyenda { get; set; }
        public string codfactura_web { get; set; }
    }
}