// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class vegrupo_objetivo
    {
        public string codgrupo { get; set; }
        public string descgrupo { get; set; }
        public double objetivo_kg { get; set; }
        public int anio { get; set; }
        public int mes { get; set; }
    }
}