// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class velog_estado_pedido
    {
        public string idproforma { get; set; }
        public int? nroidproforma { get; set; }
        public string estado { get; set; }
        public DateTime? fechareg { get; set; }
        public string horareg { get; set; }
        public string usuarioreg { get; set; }
        public int codigo { get; set; }
    }
}