// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class venotacredito_iva
    {
        public int? codnotacredito { get; set; }
        public decimal? porceniva { get; set; }
        public decimal? total { get; set; }
        public decimal? porcenbr { get; set; }
        public decimal? br { get; set; }
        public decimal? iva { get; set; }
    }
}