// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class veobjetivo_logrado_externo
    {
        public int anio { get; set; }
        public int mes { get; set; }
        public string codvendedor { get; set; }
        public decimal porcentaje_logrado { get; set; }
    }
}