// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class veplanpago
    {
        public int codigo { get; set; }
        public string descripcion { get; set; }
        public byte estadop { get; set; }
        public string moneda { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string Usuarioreg { get; set; }
        public int? diasextrappnc { get; set; }
    }
}