// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class veproforma_anticipo_diferencias
    {
        public int codigo { get; set; }
        public int? codproforma { get; set; }
        public decimal? monto { get; set; }
        public decimal? tdc { get; set; }
        public DateTime? fechareg { get; set; }
        public string usuarioreg { get; set; }
        public string horareg { get; set; }
        public bool? anticipo_aplicado_mayor { get; set; }
    }
}