// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class veproforma_anticipo1
    {
        public int codigo { get; set; }
        public int? codproforma { get; set; }
        public int? codanticipo { get; set; }
        public string monto { get; set; }
        public string tdc { get; set; }
        public string fechareg { get; set; }
        public string usuarioreg { get; set; }
        public string horareg { get; set; }
    }
}