// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class vepromventas_grupo_cfg1
    {
        public int codigo { get; set; }
        public int? codpromventas_grupo_cfg { get; set; }
        public string titulo { get; set; }
        public DateTime? de { get; set; }
        public DateTime? a { get; set; }
        public string titulo_reporte { get; set; }
        public int? nro { get; set; }
        public string codmoneda { get; set; }
        public bool incluir { get; set; }
        public bool promediar { get; set; }
    }
}