// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class veproforma_etiqueta
    {
        public int codigo { get; set; }
        public string id_proforma { get; set; }
        public int nroid_proforma { get; set; }
        public int? codalmacen { get; set; }
        public string codcliente_casual { get; set; }
        public string codcliente_real { get; set; }
        public DateTime? fecha { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public string latitud_entrega { get; set; }
        public string longitud_entrega { get; set; }
        public string horareg { get; set; }
        public DateTime? fechareg { get; set; }
        public string usuarioreg { get; set; }
    }
}