// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class verecuperacion
    {
        public int? codalmacen { get; set; }
        public byte? mes { get; set; }
        public int? anio { get; set; }
        public int? codtarifa { get; set; }
        public decimal? monto { get; set; }
        public string codmoneda { get; set; }
    }
}