// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class veruta_cliente
    {
        public string codruta { get; set; }
        public int? orden { get; set; }
        public string codcliente { get; set; }
        public string obs { get; set; }
        public decimal? tpo_atencion { get; set; }
        public decimal? tpo_total { get; set; }
        public string tipo_horario { get; set; }
        public string direccion { get; set; }
    }
}