// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class vesoldsctos
    {
        public int codigo { get; set; }
        public int? codalmacen { get; set; }
        public int? codvendedor { get; set; }
        public DateTime? fecha { get; set; }
        public string codcliente { get; set; }
        public string obs { get; set; }
        public string horareg { get; set; }
        public DateTime? fechareg { get; set; }
        public string usuarioreg { get; set; }
        public string id { get; set; }
        public int? numeroid { get; set; }
        public bool? para_venta_especial { get; set; }
        public string idproforma { get; set; }
        public int? numeroid_proforma { get; set; }
        public int? codremision { get; set; }
        public int? codproforma { get; set; }
    }
}