// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class vetienda
    {
        public int codigo { get; set; }
        public string codcliente { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string fax { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public int codptoventa { get; set; }
        public bool central { get; set; }
        public string obs { get; set; }
        public string horareg { get; set; }
        public DateTime fechareg { get; set; }
        public string usuarioreg { get; set; }
        public string aclaracion_direccion { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string telefono_2 { get; set; }
        public string celular_2 { get; set; }
        public string celular_3 { get; set; }
        public string celular_whatsapp { get; set; }
        public string nomb_telf1 { get; set; }
        public string nomb_telf2 { get; set; }
        public string nomb_cel1 { get; set; }
        public string nomb_cel2 { get; set; }
        public string nomb_cel3 { get; set; }
        public string nomb_whatsapp { get; set; }
    }
}