// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class veticket
    {
        public string id { get; set; }
        public string descripcion { get; set; }
        public int? nroactual { get; set; }
        public int? tope { get; set; }
        public string efecto { get; set; }
        public string host { get; set; }
        public string alfa { get; set; }
        public string pcsonido { get; set; }
        public bool? conecta { get; set; }
        public int? codalmacen { get; set; }
    }
}