// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class veventas_cliente
    {
        public string codcliente { get; set; }
        public int? anio { get; set; }
        public int? mes { get; set; }
        public decimal? total_mes_us { get; set; }
        public decimal? total_mes_kg { get; set; }
        public int? semana { get; set; }
        public decimal? venta_us { get; set; }
        public decimal? venta_kg { get; set; }
        public string tipo { get; set; }
        public int? codvendedor { get; set; }
        public decimal? crecimiento { get; set; }
    }
}