// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace siaw_DBContext.Models
{
    public partial class vevendedor_destinatarios
    {
        public int codigo { get; set; }
        public int codvendedor { get; set; }
        public string destinatarios { get; set; }
    }
}